### ISSUE TITLE
Linux build breaks with gcc prior to 4.7 as those versions don't have __atomic builtins

### ISSUE THREAD

**Issue by Diadlo** [the-tcpdump-group/libpcap#1003]
**libpcap version:** master (ee9955e4184702b966d95c8bef168459796e7edd)
**OS:** Arch Linux x86_64
**Compiler:** gcc from mipsel_gcc_4.6.3 toolchain
**Configure command:** `./configure --host x86_64-linux --build mipsel-linux --without-gcc`
**Steps to reproduce:** run `make`

[`pcap-linux.c`](https://github.com/the-tcpdump-group/libpcap/blob/ee9955e4184702b966d95c8bef168459796e7edd/pcap-linux.c) uses `__atomic` buildins which are [GCC C Extensions](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fatomic-Builtins.html).

But they are used even if libpcap configured with `--without-gcc` flag.

**Comment by infrastation** [comment]
It looks like Clang [supports](https://releases.llvm.org/5.0.2/docs/Atomics.html#libcalls-atomic) these GCCisms as well, and on Linux only GCC and Clang are currently the compilers of concern, so this code should not cause a problem. Does it?

**Comment by guyharris** [comment]
> **Compiler:** gcc from mipsel_gcc_4.6.3 toolchain
> **Configure command:** `./configure --host x86_64-linux --build mipsel-linux --without-gcc`

I guess it's not compiling "without GCC"....

**Comment by guyharris** [comment]
BTW, is there any reason whatsoever to have `--with-gcc`/`--without-gcc`?  That may have been reasonable back when a number of platforms offered a choice of "vendor compiler vs. GCC", but we now have some platforms that either 1) only ship with Clang (macOS+Xcode, where "gcc" runs Clang), 2) offer both GCC and Clang (many Linux distributions, as far as I know), or 3) offer GCC and a vendor compiler *and* Clang.

So maybe the right answer is "if you want a particular compiler, set CC when you run autoconf (or something equivalent for CMake)".

**Comment by guyharris** [comment]
As for `__atomic_rooster`, `__atomic_blonde`, etc.:

- the GCC 4.0.4 manual doesn't mention any atomic operations in its "Built-in functions for atomic memory access" section;
- the GCC 4.1.2, 4.2.4, 4.3.6, 4.4.7, 4.5.7, and 4.6.4 manuals mention only some older `__sync` builtins in that section;
- the GCC 4.7.4 manual mentions them in "Legacy __sync built-in functions for atomic memory access" and mention the `__atomic` operations in "Built-in functions for memory model aware atomic operations";

so you're not going to get them in 4.6.3 unless somebody's backported them to the 4.6.3 you're using.

**Comment by guyharris** [comment]
So I've added autotools and CMake checks to see whether the compiler supports the __atomic builtins, and a change to pcap-linux.c so that, if it *doesn't* support them, we define them as macros that do *non*-atomic loads and stores.  (I'm not sure whether the atomicity is necessary or sufficient - see the discussion in #898; if it *is* necessary, anybody stuck with an older version of GCC will have to figure out how to make it work with whatever atomic operations their version of GCC supports.)

I've backported the changes to the 1.10 branch, so if we put out a 1.10.1 release (which I think we should, as there are other bug fixes as well), the fix will be in that release.
