### ISSUE TITLE
There's no automated test suite for libpcap

### ISSUE THREAD

**Issue by kloczek** [the-tcpdump-group/libpcap#1012]
Looks like test suite has not been integrated with cmake.
```console
[tkloczko@barrel libpcap-1.10.0]$ /usr/bin/make -O -j48 V=1 VERBOSE=1 -C x86_64-redhat-linux-gnu test ARGS=--output-on-failure
make: *** No rule to make target 'test'.  Stop.
[tkloczko@barrel x86_64-redhat-linux-gnu]$ ctest -vv
Test project /home/tkloczko/rpmbuild/BUILD/libpcap-1.10.0/x86_64-redhat-linux-gnu
No tests were found!!!
```

**Comment by guyharris** [comment]
To which "test suite" are you referring?

**Comment by kloczek** [comment]
libpcap test suite when cmake is used to build it.
ctest is not able to find any test units. When test suite is integrated into cmake files `test` target is available.

**Comment by guyharris** [comment]
If by "test suite" you mean an automated test suite, then there's no test suite because *there's no test suite*.

I.e., the first page of fixing this bug would be to *develop a test suite for libpcap* - there's no test suite when CMake is used to build it, and there's no test suite when autotools is used to build it.

**Comment by kloczek** [comment]
In source tree there ate two directories `testprogs/` and `tests/`.
Looks like some bits from those resources could be used to provide some minimal set of test just generated binaries and I see that for example Fedora is using those resources.

**Comment by guyharris** [comment]
> In source tree there ate two directories `testprogs/`

A directory containing programs, most of which I wrote to allow me to *manually* test some features during development; they were *not* designed as automated test tools.

> and `tests/`

A directory containing, currently, a single file that was moved from tcpdump's `tests` directory, because it wasn't a useful test of tcpdump's dissection of packets - it's a pcapng file with a malformed Section Header Block at the beginning, so tcpdump can't even *open* it.  It was put there in case we decided to have similar tests for libpcap; for that file, the test would be to make sure that we correctly reject attempts to open and read the file.

> Looks like some bits from those resources could be used to provide some minimal set of test just generated binaries and I see that for example Fedora is using those resources.

Yes, somebody could do that.

> and I see that for example Fedora is using those resources.

Where do they do that?  I didn't see any indication of any such test in [the 32-bit x86 build log](https://kojipkgs.fedoraproject.org//packages/libpcap/1.10.0/1.fc35/data/logs/i686/build.log) or [the source RPM](https://kojipkgs.fedoraproject.org//packages/libpcap/1.10.0/1.fc35/src/libpcap-1.10.0-1.fc35.src.rpm) for [the libpcap-1.10.0-1.fc35 package](https://koji.fedoraproject.org/koji/buildinfo?buildID=1707834).

**Comment by kloczek** [comment]
> A directory containing programs, most of which I wrote to allow me to manually test some features during development; they were not designed as automated test tools.

Remember that testing in test suites could be about different aspects not only functional but testing DSOs ABI and library API.
From that point of view when I'm packaging different stuff I'm trying sometimes enable build examples even if those examp.es would be not used or installed.
From exactly that point point of view those programs are already designed to be used as playground for testing libpcap 😊
I've added building those programs in my rpm %check section the same way as it is done in Fedora packages.

**Comment by infrastation** [comment]
Let's close it then. Please follow up on the mailing list if you wish.
