### ISSUE TITLE
How can i interrupt "scanning 80211 packets" safely to change channel and continue scanning ?

### ISSUE THREAD

**Issue by linxcow** [the-tcpdump-group/libpcap#1030]
I'm using code below to do the scanning without changing channels                          

                          [char error_buffer[PCAP_ERRBUF_SIZE];
                          pcap_t *h = pcap_create("wlan0", error_buffer);
                          pcap_set_rfmon(h, 1);
                          pcap_activate(h);
                          pcap_loop(h, -1, processPacket, NULL)

My goal would be to change channel every 250msecs using linux iwconfig

**Comment by mcr** [comment]
this is not really a libpcap problem.
This is a kernel problem, in that you (I'm pretty sure) have to take the interface down to change channels, and doing that closes the capture.
If you want to be able to change channels without taking the interface down,  then you probably need to find a way to teach the kernel to do that.

**Comment by linxcow** [comment]
I just tried and was able to set the channel without taking down the interface.
So there must be a way achieve what im trying to do?

        sudo iwconfig wlan2 channel 2
        sudo iw dev
    result :

           Interface wlan2
                ifindex 16
                wdev 0xa00000001
                addr 00:c0:ca:99:12:8f
                type monitor
                channel 2 (2417 MHz), width: 20 MHz (no HT), center1: 2417 MHz
                txpower 20.00 dBm

**Comment by guyharris** [comment]
I assume from "scanning 80211 packets" being in quotes that it's a message that some software is producing.

What software is producing the "scanning 80211 packets" message?  A case-insensitive search for 'scanning.*802.*11 packets' doesn't find it in the Linux 5.6.7 kernel, the main branch in libpcap, the main branch in tcpdump, or the main branch in Wireshark.

**Comment by linxcow** [comment]
To clarify I'm capturing probe-request frames using an interface in monitor mode , with a c program using the libpcap functions mentioned in the above post.

**Comment by guyharris** [comment]
> To clarify I'm capturing probe-request frames using an interface in monitor mode , with a c program using the libpcap functions mentioned in the above post.

So is *your* program printing that message?

**Comment by linxcow** [comment]
It is a not message , but it tries to describe what my program is doing .

**Comment by guyharris** [comment]
So is your question "how do I interrupt my program's reading loop every every 250 ms?" or is it "how do I change the channel?", or do you need to know both?

**Comment by linxcow** [comment]
> So is your question "how do I interrupt my program's reading loop every every 250 ms?" 

yes

loop:
- capture packets for 250ms
- change channel
- goto loop:

**Comment by guyharris** [comment]
I'm assuming from "wlan0" that this is on Linux, so here are some possibilities:

1. Put the `pcap_t` in non-blocking mode, have the loop use `select()`/`poll()`/`epoll()` (I'm assuming from "wlan0" that this is on Linux) with a 250 ms timeout.  If the timeout has occurred, change the channel.  If the `pcap_t`'s descriptor (obtained with `pcap_get_selectable_fd()`) is readable, call `pcap_dispatch()` on the `pcap_t` to process the packets that are currently available.  (If both are the case, do both.)
2. If you're running on a sufficiently recent Linux kernel to have "timers that notify via file descriptors", create a time with [`timerfd_create()`](https://man7.org/linux/man-pages/man2/timerfd_create.2.html) and set it to deliver a notification every 250 ms, put the `pcap_t` in non-blocking mode, have the loop use `select()`/`poll()`/`epoll()`with both the descriptor from `pcap_get_selectable_fd()` and the timer descriptor and without the 250 ms timeout, and do the same as the previous possibility (this one makes it a little easier to determine whether the timeout occurred or not).
3. Use `setitimer()` to set up a signal routine that gets called every 250 ms, and have that routine call `pcap_breakloop()` on the `pcap_t`.  Instead of a single call to `pcap_loop()`, have a loop that repeatedly calls `pcap_loop()`, and, if it returns, check whether the signal routine got called and, if so, change the channel.

The second of those is probably the simplest and cleanest, but only works if you *have* `timerfd_create()`.

**Comment by linxcow** [comment]
Hi Guy ,

Thank you for these possible solutions , highly appreciated ,Its running on a raspberry with raspbian .

Which of these options should have the least chance of packet loss , also I've read that nonblocking can waste a lot of resources in the loop. 

            Host: raspberrypi Kernel: 5.10.17-v7l+ armv7l bits: 32 compiler: N/A
            Console: tty 0 dm: N/A Distro: Raspbian GNU/Linux 10 (buster)

**Comment by guyharris** [comment]
> Which of these options should have the least chance of packet loss

The difference should be minimal.

> also I've read that nonblocking can waste a lot of resources in the loop. Is that correct?

Not if it's done correctly.

If you have a loop that doesn't do any `select()`/`poll()`/`epoll()`/`kqueue()`/`WaitForMultipleObjects()`/etc.-style "wait for" operation on the FD (UN\*X)/HANDLE (Windows) for the `pcap_t`, the loop will spin, eating CPU time, doing nothing useful if no packets are arriving.

However, if you *do* have a "wait for" call in your loop, as suggestions 1 and 2 do, that won't happen.

On most platforms, doing that call will add an additional system call to the code path for processing packets - one "wait for" call, followed by a read call.

Linuxes that support memory-mapped packet capture - and that dates back to some 2.x kernel, so any *modern* Linux should support it - is *not* one of those platforms.  For that, there's no read call; there's just a `poll()` call done inside libpcap, to wait for packets, if the `pcap_t` is not in non-blocking mode; that call is *not* done in non-blocking mode, so there would be only one system call per batch of packets.

**Comment by FeldrinH** [comment]
@guyharris 
> there's just a `poll()` call done inside libpcap, to wait for packets, if the `pcap_t` is not in non-blocking mode; that call is _not_ done in non-blocking mode, so there would be only one system call per batch of packets.

This is obviously a fairly minor point, but I want to make sure that I understand everything correctly:

You say that in non-blocking mode the `poll` call is not done, but looking at the code it seems that it is (see https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-linux.c#L3531-L3536). Does this mean that there is in fact an extra syscall if you use non-blocking mode (one syscall to wait for packets and one `poll` call in libpcap to check for errors)?
