### ISSUE TITLE
Duplicated CAN packages 

### ISSUE THREAD

**Issue by Elfoniok** [the-tcpdump-group/libpcap#1051]
Hello some time ago, quite a long time but we are creating embedded systems and don't upgrade packages that often. But we did eventually and now we are on 1.8.1.

We noticed that libpcap dropped the implementation of pcap-can-linux.c

https://github.com/the-tcpdump-group/libpcap/commit/93ca5ff7030aaf1219e1de05ec89a68384bfc50b

This was unfortunate for us because new method using cooked mode cause the CAN logs created by libpcap to extend in size twice as much (the CAN frame was 16b now with additional LL its 32b)

So we thought we changed the DLT_LINUX_SLL to DLT_SOCKET_CAN for our libpcap. But this cause couple of problems, mainly duplicated packets issue.

I have noticed following patch
https://github.com/the-tcpdump-group/libpcap/commit/ae94350551861bbefb52f10c4ba499c1440a6a10

I discovered that indeed we receive a lot of duplicates packets on ring buffer. That is, even with this patch, so something else had to be wrong. 

The packet capture on our system is using pcap_handle_packet_mmap (via v3 function), but because of our patch, cooked mode is not set. The problem is that the check direction function is using sll->sll_protocol to drop loopback duplicates. The problem is that on our system this value seems to be in LE byte order. After application the htons to sll->sll_protocol we receive expected value (000C before it was C00). And that solves the issue.

I was wondering if that is generic problem, or something caused by our patch (essentialy using DLT_SOCKET_CAN for can interfaces)? We also had to apply htons to canid.

Other question is if no one else is bothered that can dumps take twice as much space as they used to be?

**Comment by Elfoniok** [comment]
Attaching patch for enabling DLT_SOCKET_CAN
[Use-SocketCAN-as-data-link-type-of-CAN-frame.txt](https://github.com/the-tcpdump-group/libpcap/files/7215460/Use-SocketCAN-as-data-link-type-of-CAN-frame.txt)

**Comment by guyharris** [comment]
> So we thought we changed the DLT_LINUX_SLL to DLT_SOCKET_CAN for our libpcap.

Presumably by `DLT_SOCKET_CAN` you mean `DLT_CAN_SOCKETCAN`.  There is no `DLT_SOCKET_CAN` in libpcap.

If *all* you did was to change a reference to `DLT_LINUX_SLL` to `DLT_CAN_SOCKETCAN`, that won't work, as you won't get headers that look like [`DLT_CAN_SOCKETCAN` headers](https://www.tcpdump.org/linktypes/LINKTYPE_CAN_SOCKETCAN.html) if you're capturing on a CAN interface using a `PF_PACKET` socket in cooked mode.

> The packet capture on our system is using pcap_handle_packet_mmap (via v3 function), but because of our patch, cooked mode is not set.

OK, so you didn't just change `DLT_LINUX_SLL` to `DLT_CAN_SOCKETCAN`, you also turned off cooked mode for capturing on CAN devices, presumably in order to strip off the `DLT_LINUX_SLL` header.

> The problem is that the check direction function is using sll->sll_protocol to drop loopback duplicates. The problem is that on our system this value seems to be in LE byte order.

So is the CPU on your embedded system running in big-endian or little-endian mode?

And if you *don't* turn off cooked mode, and you use `DLT_LINUX_SLL`, do you still have a problem with duplicates?

**Comment by Elfoniok** [comment]
Sorry I guess I was imprecise. Yes I meant DLT_CAN_SOCKETCAN. 

Could you please refer to patch attached? That is basically all we did. The code is actually parts of original implementation before switch to SLL. 

Its pretty much just setting DLT_CAN_SOCKETCAN in place of DLT_LINUX_SLL. And it actually is working that is we can see the can header correctly, its just the byte orders is reveresd once more, for CAN ID.

When I wrote "because of our patch" I meant switching DLT. I guess cooked mode is disabled then. Sorry I didn't check why. The if (handlep->cooked) is just not executing in pcap_handle_packet_mmap.

The CPU is LE. We get the sll_protocol value as 0C00 (3072) where it should be 000C (12).

**Comment by guyharris** [comment]
Changes acc5cb90d78e467ccaa24953f6a729c623a99f25 in the main branch and fa91341ab7647521c90b3e34c93026725bfb71dd in the 1.10 branch should address the duplicate packet problem.

**Comment by Elfoniok** [comment]
Thanks! I will try that tomorrow its late here.

**Comment by Elfoniok** [comment]
Yes I see the protocol is recognized correctly now, and I no longer see duplicates.

**Comment by guyharris** [comment]
Changes 4357b2d0edbb6371906af2179cf3497e6e1db78a and 436179a5f5ff3924ee7285777777a4f71372f654 in the main branch cause DLT_CAN_SOCKETCAN rather than DLT_LINUX_SLL to be used for CAN devices, and use the CANFD_FDF bit in the FD flags field of the CAN header to indicate whether the frame is a CAN frame or a CAN FD frame.

Note that, currently, *no* version of Wireshark understands that flag, so you may not want to be *too* quick to adopt that version of the pcap-linux.c code.  For that and other reasons, I'm not going to backport this change to the 1.10 branch.

**Comment by guyharris** [comment]
BTW, your patch byte-swaps the CAN ID and flags field when processing a `DLT_CAN_SOCKETCAN` packet, but it shouldn't do that.  If it's a `DLT_LINUX_SLL` or `DLT_LINUX_SLL2` packet, the CAN ID and flags are in host byte order, but if it's a `DLT_CAN_SOCKETCAN` packet, the CAN ID and flags are in *network* byte order, so it should be left alone.

**Comment by guyharris** [comment]
> Note that, currently, no version of Wireshark understands that flag, so you may not want to be too quick to adopt that version of the pcap-linux.c code. For that and other reasons, I'm not going to backport this change to the 1.10 branch.

Support for the flag was added to the main branch of Wireshark, and backported to the 3.6 and 3.4 branches; the latest 3.4 and 3.6 releases (3.4.12, 3.6.2) have it.

I've backported this and other updates to the CAN support to the 1.10 branch of libpcap; tcpdump doesn't currently support `LINKTYPE_SOCKETCAN`/`DLT_SOCKETCAN` - if it's ever added, it'll support all the changes.
