### ISSUE TITLE
Dont add DLT_LINUX_SLL headers for CAN dumps.

### ISSUE THREAD

**Issue by Elfoniok** [the-tcpdump-group/libpcap#1052]
After replacing DLT_CAN_SOCKETCAN with DLT_LINUX_SLL, can dumps now records pseudo link layer header. This extend the size of the logs twofold.

I am wondering if it would be possible to add "save space" mode for can dumps? So it either strip SLL headers or use DLT_CAN_SOCKETCAN.

**Comment by guyharris** [comment]
We switched to cooked mode for `ARPHRD_CAN` in commit 93ca5ff7030aaf1219e1de05ec89a68384bfc50b in order to allow readers to distinguish between CAN and CAN FD:

```
commit 93ca5ff7030aaf1219e1de05ec89a68384bfc50b
Author: Guy Harris <gharris@sonic.net>
Date:   Thu Aug 25 13:26:43 2016 -0700

    On Linux, handle all CAN captures with pcap-linux.c, in cooked mode.

    There's no need to support capturing on PF_CAN sockets; CAN interfaces
    show up as regular interfaces on which you can capture with PF_PACKET
    sockets, so just let pcap-linux.c handle them, and get rid of
    pcap-can-linux.c.

    Capture on them in cooked mode, so we get the protocol field and can
    distinguish between "classic" CAN and CAN FD.

    The hardware for which pcap-canusb-linux.c was intended never reached
    production:

        https://github.com/axos88/libpcap/commit/f3edbb599b8cbcc7e4560000dcba8e$

    so we don't need pcap-canusb-linux.c, either.

    This all removes the need for the "host-endian" link-layer header type;
    it never made it into a libpcap release, so we just remove it.  The
    "big-endian" link-layer header type is kept for the benefit of packets
    captured with the old pcap-can-linux.c code; we revert it to its old
    name.
```

[The Linux kernel added a bit in the flags in the SocketCAN header that's never set by the kernel, but that is reserved for flagging frames as CAN or CAN FD](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net-next.git/commit/?id=02546884221279da2725e87e35348290470363d7), so there's now a way to distinguish between them without the `DLT_LINUX_SLL` pseudo-header.

So we could switch back to `DLT_CAN_SOCKETCAN`, and, for each CAN packet received:

- put the CAN ID and flags field in host byte order;
- set the `CANFD_FDF` in the FD flags field (which was the first padding byte after the CAN ID and flags field) if `sll_protocol` is `LINUX_SLL_P_CANFD`;

and wouldn't need to add a mode.

**Comment by guyharris** [comment]
BTW, your patch byte-swaps the CAN ID and flags field when processing a `DLT_CAN_SOCKETCAN` packet, but it shouldn't do that.  If it's a `DLT_LINUX_SLL` or `DLT_LINUX_SLL2` packet, the CAN ID and flags are in host byte order, but if it's a `DLT_CAN_SOCKETCAN` packet, the CAN ID and flags are in *network* byte order, so it should be left alone.

**Comment by guyharris** [comment]
Changes 4357b2d0edbb6371906af2179cf3497e6e1db78a and 436179a5f5ff3924ee7285777777a4f71372f654 in the main branch cause DLT_CAN_SOCKETCAN rather than DLT_LINUX_SLL to be used for CAN devices, and use the CANFD_FDF bit in the FD flags field of the CAN header to indicate whether the frame is a CAN frame or a CAN FD frame.

Note that, currently, *no* version of Wireshark understands that flag, so you may not want to be *too* quick to adopt that version of the pcap-linux.c code.  For that and other reasons, I'm not going to backport this change to the 1.10 branch.
