### ISSUE TITLE
Build with static DPDK libraries fails when building testprogs

### ISSUE THREAD

**Issue by MalekChebli** [the-tcpdump-group/libpcap#1097]
hello,
I'm trying to compile libpcap with DPDK with this command "mkdir -p build && cd build && cmake -DDPDK_DIR=$RTE_SDK/$RTE_TARGET ../ && make -s all && make -s testprogs && make install"
but I found these errors : 
![image](https://user-images.githubusercontent.com/100672682/157048846-a6bc27bc-fccd-4a99-8168-15e2de706bc5.png)

Could you please help me to solve them.
Thank you in advance.

**Comment by infrastation** [comment]
Could you provide specific steps to reproduce the problem?

**Comment by infrastation** [comment]
Please study the file `CONTRIBUTING.md` (as advised in the issue template for all new issues) and provide more information about the problem. Also please do not use `sudo` to compile the source.

**Comment by guyharris** [comment]
> I went to the directory '/home/libpcap/build' in order to compile libpcap

I'm seeing "/home/pfedpdk/libpcap/build", not "home/libpcap/build", in at least one of the screenshots.  In what directory is the source, and in what directory are you doing the build?

**Comment by guyharris** [comment]
> and I got this error with the following missing libraries (DAG, TC, SNF, Airpcap) when they already exists in the same directory

Neither TC or AirPcap exist unless you're building for Windows.  There are CMake modules to *search* for them, but that's because the source contains CMake modules for everything that we want CMake to search for, even if it's not available on some particular platform.

DAG only exists if you have an Endace DAG card and you've gotten the DAG library; again, we have a CMake module to detect it, but that doesn't mean it's guaranteed to detect it.

SNF only exists if you have a Myricom adapter that supports their SNF software; the same applies.

And those aren't *errors* - they don't prevent CMake from completing.  They're just notifications.

**Comment by guyharris** [comment]
> Also please do not use `sudo` to compile the source.

@infrastation is correct here.  Not only is building as root risky, as it runs commands as root, it can *also* mean that some files and directories in your build tree require root permission to write to, meaning that running CMake, or a build, as yourself, rather than as root, may fail with permission errors.

That might be the cause of the permission errors you saw.  I suggest that:

1. you remove all the libpcap build directories that you have (which may require `sudo rm -rf` if any of them were written to by a build done as root);
2. if you're building from the libpcap Git repository, do a `git pull` to make it up-to-date;
3. make a new build directory, *as yourself, not as root*;
4. run CMake from the build directory, *as yourself, not as root*;
5. if that succeeds, do a build, *as yourself, not as root*.

**Comment by guyharris** [comment]
To quote the first screenshot you posted (which I read and typed into a file from which I copied to the clipboard - *don't* paste screenshots of plain text, make sure the plain text is put somewhere from which you can copy and paste into an issue, so that I don't have to go through this painful and error-prone process):

```
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/librte_eal.a(librte_eal_common_eal_common_options.c.o): undefined reference to symbol 'dlopen@GLIBC_2.2.5'
/usr/bin/ld: /lib/x86_64-linux-gnu/libdl.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [testprogs/fuzz/CMakefiles/fuzz_both.dir/build.make:123: run/fuzz_both] Error 1
make[1]: *** [CMakeFiles/Makefile2:596: testprogs/fuzz/CMakeFiles/fuzz_both.dir/all] Error 2
make: *** [Makefile:150: all] Error 2
```

So the error appears to occur in "make testprogs", where it's trying to link a fuzz-testing program, and, according to [this page](https://zhangboyi.gitlab.io/post/2020-09-14-resolve-dso-missing-from-command-line-error/)'s explanation, it appears to be a complaint that something in librte_eal_common_eal_common_options.c called `dlopen()` but that function isn't defined in any library mentioned on the command line - however, it's defined in some library upon which one of those other libraries depends.

See also [this Stack Overflow question](url) and its answers.

To quote from [your Stack Overflow question](https://stackoverflow.com/questions/71480628/usr-bin-ld-cannot-find-ldpdk?noredirect=1#comment126473537_71480628):

> I'm trying to link static dpdk

Sadly, DPDK includes calls to `dlopen()`.  If I try to compile the small program

```
$ cat small_static.c
#include <stddef.h>
#include <dlfcn.h>

int
main(void)
{
	void *dl;

	dl = dlopen("kernel32.dll", 0);
	return (dl == NULL) ? 1 : 0;
}
```

with

```
$ cc -static -o small_static small_static.c -ldl
```

on Ubuntu 20.04, it gives me the warning:

```
/bin/ld: /tmp/ccbnG20P.o: in function `main':
small_static.c:(.text+0x19): warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

Using `dlopen()` in a static *library* also causes some surprising consequences:

```
ubu20-04$ cc -static -o static `pkg-config --cflags --static libdpdk` static.c `pkg-config --libs --static libdpdk`
ubu20-04$ file ./static
./static: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, BuildID[sha1]=973eb925851c9091f277ee10fa2e82e865f59489, for GNU/Linux 3.2.0, not stripped
```

I.e., I wrote a small program in "static.c" (it's a copy of all the external includes from pcap-dpdk.c, plus a call to `rte_eal_init()`, to drag in at least one routine that's used by the DPDK support for libpcap), and compiled it with the C compiler flags that the DPDK pkg-config file says should be used for static compilation:

```
$ pkg-config --cflags --static libdpdk
-include rte_config.h -march=corei7 -I/usr/include/dpdk/../x86_64-linux-gnu/dpdk -I/usr/include/dpdk -I/usr/include/libnl3
```

and the linker flags that the DPDK pkg-config file says should be used for static compilation:

```
$ pkg-config --libs --static libdpdk
include rte_config.h -march=corei7 -I/usr/include/dpdk/../x86_64-linux-gnu/dpdk -I/usr/include/dpdk -I/usr/include/libnl3
ubu20-04$ pkg-config --libs --static libdpdk
-lrte_telemetry -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_rcu -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_ring -lrte_eal -lrte_kvargs -Wl,--whole-archive -lrte_common_cpt -lrte_common_dpaax -lrte_common_octeontx -lrte_common_octeontx2 -lrte_bus_dpaa -lrte_bus_fslmc -lrte_bus_ifpga -lrte_bus_pci -lrte_bus_vdev -lrte_bus_vmbus -lrte_mempool_bucket -lrte_mempool_dpaa -lrte_mempool_dpaa2 -lrte_mempool_octeontx -lrte_mempool_octeontx2 -lrte_mempool_ring -lrte_mempool_stack -lrte_rawdev_dpaa2_cmdif -lrte_rawdev_dpaa2_qdma -lrte_rawdev_ioat -lrte_rawdev_ntb -lrte_rawdev_octeontx2_dma -lrte_rawdev_skeleton -lrte_pmd_af_packet -lrte_pmd_ark -lrte_pmd_atlantic -lrte_pmd_avp -lrte_pmd_axgbe -lrte_pmd_bond -lrte_pmd_bnx2x -lrte_pmd_bnxt -lrte_pmd_cxgbe -lrte_pmd_dpaa -lrte_pmd_dpaa2 -lrte_pmd_e1000 -lrte_pmd_ena -lrte_pmd_enetc -lrte_pmd_enic -lrte_pmd_failsafe -lrte_pmd_fm10k -lrte_pmd_i40e -lrte_pmd_hinic -lrte_pmd_hns3 -lrte_pmd_iavf -lrte_pmd_ice -lrte_pmd_ifc -lrte_pmd_ixgbe -lrte_pmd_kni -lrte_pmd_liquidio -lrte_pmd_memif -lrte_pmd_mlx4 -lrte_pmd_mlx5 -lrte_pmd_netvsc -lrte_pmd_nfp -lrte_pmd_null -lrte_pmd_octeontx -lrte_pmd_octeontx2 -lrte_pmd_pcap -lrte_pmd_pfe -lrte_pmd_qede -lrte_pmd_ring -lrte_pmd_sfc -lrte_pmd_softnic -lrte_pmd_tap -lrte_pmd_thunderx -lrte_pmd_vdev_netvsc -lrte_pmd_vhost -lrte_pmd_virtio -lrte_pmd_vmxnet3 -lrte_pmd_aesni_gcm -lrte_pmd_aesni_mb -lrte_pmd_caam_jr -lrte_pmd_ccp -lrte_pmd_dpaa_sec -lrte_pmd_dpaa2_sec -lrte_pmd_nitrox -lrte_pmd_null_crypto -lrte_pmd_octeontx_crypto -lrte_pmd_octeontx2_crypto -lrte_pmd_openssl -lrte_pmd_crypto_scheduler -lrte_pmd_virtio_crypto -lrte_pmd_isal -lrte_pmd_octeontx_compress -lrte_pmd_qat -lrte_pmd_zlib -lrte_pmd_dpaa_event -lrte_pmd_dpaa2_event -lrte_pmd_octeontx2_event -lrte_pmd_opdl_event -lrte_pmd_skeleton_event -lrte_pmd_sw_event -lrte_pmd_dsw_event -lrte_pmd_octeontx_event -lrte_pmd_bbdev_null -lrte_pmd_bbdev_turbo_sw -lrte_pmd_bbdev_fpga_lte_fec -Wl,--no-whole-archive -Wl,--export-dynamic -lrte_telemetry -lrte_bpf -lrte_flow_classify -lrte_pipeline -lrte_table -lrte_port -lrte_fib -lrte_ipsec -lrte_vhost -lrte_stack -lrte_security -lrte_sched -lrte_reorder -lrte_rib -lrte_rcu -lrte_rawdev -lrte_pdump -lrte_power -lrte_member -lrte_lpm -lrte_latencystats -lrte_kni -lrte_jobstats -lrte_ip_frag -lrte_gso -lrte_gro -lrte_eventdev -lrte_efd -lrte_distributor -lrte_cryptodev -lrte_compressdev -lrte_cfgfile -lrte_bitratestats -lrte_bbdev -lrte_acl -lrte_timer -lrte_hash -lrte_metrics -lrte_cmdline -lrte_pci -lrte_ethdev -lrte_meter -lrte_net -lrte_mbuf -lrte_mempool -lrte_ring -lrte_eal -lrte_kvargs -Wl,-Bdynamic -pthread -lm -ldl -lnuma -lfdt -lpcap -lIPSec_MB -lmlx4 -lpthread -lmlx5 -lpthread -libverbs -lbnxt_re-rdmav25 -lcxgb4-rdmav25 -lefa -lhns-rdmav25 -li40iw-rdmav25 -lmlx4 -lmlx5 -lmthca-rdmav25 -locrdma-rdmav25 -lqedr-rdmav25 -lvmw_pvrdma-rdmav25 -lhfi1verbs-rdmav25 -lipathverbs-rdmav25 -lrxe-rdmav25 -lsiw-rdmav25 -libverbs -lpthread -lnl-route-3 -lnl-3 -lpcap -lcrypto -ldl -pthread -lisal -ljansson -lelf -lz -lbsd
```

(I am not kidding, that's *exactly* what was printed by that command, with *all* those libraries!).

Note that the flags include `-Wl,-Bdynamic`, meaning "link with the *shared* versions, not the *static* versions, of all the libraries after this", as well as `-ldl`, meaning "link with the library that you need if you're doing to use `dlopen()` and `dlsym()`, both of which are used in some parts of the DPDK libraries (libraries, plural - I counted about 117 or so of them!) to load code at run time.

I.e., it overrode the `-static` and produced a dynamically-linked program *anyway*.

As the warning the linker printed when I tried to link my first test program statically says:

> Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

So, if you're trying to link with a static version of the DPDK libraries, and your program, *or any of the libraries the program calls*, ends up calling one of the routines in the DPDK libraries that does a `dlopen()`, *your program will have to be dynamically linked with the C library, so that it has access to the code that implements `dlopen()`.  It will *also* have to be linked with `-ldl`, as that's the library in which `dlopen()` is defined.

I.e., "static" and "DPDK libraries" are not a good match.

**Comment by infrastation** [comment]
This will be closed in 7 days unless the reporter can demonstrate that there still is a problem and the above detailed explanation does not address it fully.

**Comment by infrastation** [comment]
It is time.
