### ISSUE TITLE
Use .dll or .lib file with gcc 4.8.3 to compile my software that uses <pcap/pcap.h> on Windows 10

### ISSUE THREAD

**Issue by govwin** [the-tcpdump-group/libpcap#1106]
I have written a software on Ubuntu and has line `#include <pcap/pcap.h>` which works flawless.  Now I cannot find a way to compile and run it on Windows. 
On Windows 10, I'm using Visual Studio Code, gcc version 4.8.3 and trying to compile and build executable using g++.
I have followed instructions in https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.Win32.md and successfully created pcap.dll, pcap.lib and pcap_static.lib on Visual Studio 2019. 
I tried to build my software in `cmd` console using `g++ -std=c++11 -g source.cpp <path to dll>/pcap.dll -o output.exe` which gives `fatal error: pcap/pcap.h: No such file or directory`. After commenting that header include line, the error is `error: 'pcap_t' does not name a type`.
Please help. I don't know what to do.
libpcap version 1.x.y (I did git clone on 22nd April 2022, and that version).
operating system name and version: Windows 10 Version 20H2
Above written problem and steps to reproduce

**Comment by guyharris** [comment]
> I tried to build my software in cmd console using `g++ -std=c++11 -g source.cpp <path to dll>/pcap.dll -o output.exe` which gives fatal error: pcap/pcap.h: No such file or directory

You need to do

    g++ -std=c++11 -g -I<path to pcap source directory> source.cpp <path to dll>/pcap.dll -o output.exe

because g++ will only look in standard include directories for include files, and those directories do not include libpcap's header files on Windows.

> After commenting that header include line, the error is error: 'pcap_t' does not name a type.

That will only make things worse.  Using libpcap *requires* pcap/pcap.h.

Note also that, as the instructions in https://github.com/the-tcpdump-group/libpcap/blob/master/doc/README.Win32.md include "install the Npcap SDK", you can just build your application to use Npcap; Npcap isn't based on the version of libpcap on the tip of the main branch, but it *is* based on the libpcap 1.10.1 release, so it's up-to-date with the latest release.

For that, you do not need to compile libpcap source at all.

To do *that*, use

    g++ -std=c++11 -g -I<path to the SDK}/Include source.cpp -L<path to the SDK}/Lib -lwpcap -o output.exe

(I'm assuming here that /es in paths will work the same as \\s.)
