### ISSUE TITLE
How to use libpcap send raw ip packet at Ipv6-in-Ipv4?

### ISSUE THREAD

**Issue by chushuai** [the-tcpdump-group/libpcap#1121]
My network card is configured as follows:
 ip tunnel add isatap0 mode sit local 10.9.24.9 remote 172.16.10.100 
 ip addr add  2401:3480:3:4::10.9.24.9 dev isatap0 
 ip link set isatap0 up 
 ip route add  0::/0 dev  isatap0 

I use Libpcap to send raw ip messages. The network card prompts an error
![image](https://user-images.githubusercontent.com/5875458/185021674-cbcedd8f-bf1a-4cfc-a98a-faa15c016f3f.png)

**Comment by infrastation** [comment]
```
To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
CONTRIBUTING.md in the libpcap source tree root.
```
Please do that, and after studying the file provide a problem statement detailed as much as it says, or more.

**Comment by guyharris** [comment]
This appears to be Linux.

The code in libpcap to send packets on a Linux network interface is

```
	if (handlep->ifindex == -1) {
		/*
		 * We don't support sending on the "any" device.
		 */
		pcap_strlcpy(handle->errbuf,
		    "Sending packets isn't supported on the \"any\" device",
		    PCAP_ERRBUF_SIZE);
		return (-1);
	}

	if (handlep->cooked) {
		/*
		 * We don't support sending on cooked-mode sockets.
		 *
		 * XXX - how do you send on a bound cooked-mode
		 * socket?
		 * Is a "sendto()" required there?
		 */
		pcap_strlcpy(handle->errbuf,
		    "Sending packets isn't supported in cooked mode",
		    PCAP_ERRBUF_SIZE);
		return (-1);
	}

	ret = (int)send(handle->fd, buf, size, 0);
	if (ret == -1) {
		pcap_fmt_errmsg_for_errno(handle->errbuf, PCAP_ERRBUF_SIZE,
		    errno, "send");
		return (-1);
	}
	return (ret);
```

I'm assuming you opened the "isatap0" interface, so you're not sending on the "any" device and wouldn't have gotten the first error.

I'm also assuming that you're calling either `pcap_inject()` or `pcap_sendpacket()` (the only difference between them is the return value, and that's due to WinPcap and OpenBSD libpcap defining almost-identical "send a packet" APIs, both of which we wanted to support), and that you're checking whether they return `PCAP_ERROR` and, if they do, reporting the error and using `pcap_geterr()` to get an error string.  If not, please fix your code to do so.  Once the code does so, is it reporting "Sending packets isn't supported in cooked mode", is it reporting some other error, or is it not reporting an error?

If it's reporting "Sending packets isn't supported in cooked mode", we'd need to figure out how to allow libpcap to run in non-cooked mode on the tunnel interface.

If it's *not* reporting "Sending packets isn't supported in cooked mode", then all the code is doing is a `send()` on the `PF_PACKET` socket that libpcap creates.  If so, then:

First, have your program, after it has a usable `pcap_t` (i.e., either after `pcap_open_live()` or `pcap_create()` and `pcap_activate()` have succeeded), do

```
    int linktype = pcap_linktype(<the pcap_t *>);
    printf("Link-layer header type is %s\n", pcap_datalink_val_to_name(linktype));
```

and indicate what it prints.

Second, tell us what headers you're putting on the packet you're sending - Ethernet header followed by an IP header?  Just an IP header?

**Comment by chushuai** [comment]
Just an IP header @guyharris

**Comment by guyharris** [comment]
> I called pcap_sendpacket send packet at isatap0

What value did `pcap_sendpacket()` return?

> and send just an IP header

What value does `pcap_linktype()` return when called with the `pcap_t` you opened?

**Comment by infrastation** [comment]
Linux sit is IPv6-in-IPv4, so packets on that interface should very likely be IPv6, which can be confirmed using tcpdump.

**Comment by chushuai** [comment]
This is the tcpdump 
but The network tx error
![image](https://user-images.githubusercontent.com/5875458/185350072-810a41e7-a31d-4483-ad3a-25ed0395c40b.png)

**Comment by chushuai** [comment]
@guyharris  I used libpcap version 1.5.3, no pcap_ Linktype this function, pcap_sendpacket return 0

**Comment by guyharris** [comment]
> I used libpcap version 1.5.3, no pcap_ linktype

Sorry, I got the name wrong - it's `pcap_datalink()`, not `pcap_linktype()`.

So what does `pcap_datalink()` return?

**Comment by chushuai** [comment]
@guyharris 
pcap_datalink() return 12
Link-layer header type is RAW

**Comment by infrastation** [comment]
After re-reading my earlier comment I realized it was wrong because capturing packets on a sit interface would produce IPv4 packets (the payload) rather than IPv6 packets (the transport). This would be consistent with `DLT_RAW` and earlier comments about IPv4 payload header. However, with this in mind the Wireshark screenshot looks irrelevant, please correct me if that's not the case.

Please note that libpcap release 1.5.3 is from 9 years ago. If the problem reproduces with the latest stable release of libpcap, please post specific steps to reproduce and the source code.

**Comment by infrastation** [comment]
After re-reading all the comments again it is clear that in the previous comment I got the protocol nesting order wrong: Linux SIT is IPv6-in-IPv4, as the screenshot correctly tells. In the Wireshark screenshot the DLT seems to match the interface, and the packet is an IPv6 packet with a seemingly correct header. `pcap_sendpacket()` returns 0. All looks consistent, but there is a problem.

@chushuai, please explain the problem in more detail. The SIT interface shows 25588 Tx packets and 6221 Tx errors. Which of these counters increments by 1 every time your program tries to send the packet? Does the packet appear on the SIT interface as an IPv6 packet? Does the encapsulated IPv6-in-IPv4 packet appear on the interface through which the remote endpoint (172.16.10.100) is routable? Which Linux distribution and version is this? Do you have a minimal reproducer source code for the problem?

**Comment by guyharris** [comment]
> i called pcap_sendpacket send packet at isatap0 and send just an IP header

Does "IPv6-in-IPv4" mean a mechanism in which the outer IPv4 header uses a protocol value of 41, such as ["6in4"](https://en.wikipedia.org/wiki/6in4) or ["6to4"](https://en.wikipedia.org/wiki/6to4)?

If so, is the "IP header" the IPv6 header or an IPv4 header with a protocol value of 41 followed by the IPv6 header?

**Comment by infrastation** [comment]
Without detailed steps to reproduce this request will be closed.

**Comment by infrastation** [comment]
As discussed.
