### ISSUE TITLE
How to disable the sanitizer option while compiling libpcap using CLion and cmake?

### ISSUE THREAD

**Issue by Leaf550** [the-tcpdump-group/libpcap#1171]
I'm compiling libpcap using cmake. The libpcap will linked to my application. Here is a part of my CMakeLists.txt file:
```
include(FetchContent)

FetchContent_Declare(
        pcap
        GIT_REPOSITORY https://github.com/the-tcpdump-group/libpcap.git
        GIT_TAG libpcap-1.10.1
        SOURCE_DIR ${PROJECT_SOURCE_DIR}/ext/pcap
)
FetchContent_MakeAvailable(pcap)
```
When I click build button in CLion. There is an error occurred:
```
-- Checking C compiler flag -std=gnu99
-- Use DYNAMIC runtime
-- Support IPv6
-- Checking sanitizer OFF
CMake Error at ext/pcap/CMakeLists.txt:1030 (message):
  OFF isn't a supported sanitizer
```
I never set the sanitizer filed. But the error just occurred. Why? And how can I fix this to build my project?

**Comment by guyharris** [comment]
> I never set the sanitizer field.

Neither do we.  Perhaps CLion is "helpfully" doing something such as passing `-DENABLE_SANITIZERS=OFF`.  There may be projects where that does something that doesn't break the build, but libpcap is not one of them - the way to disable all sanitizers in libpcap is to *not pass any `-DENABLE_SANITIZERS=` argument to CMake*.

> And how can I fix this to build my project?

By waiting for us to modify our CMakeFile so that it supports setting `ENABLE_SANITIZERS` to `OFF` (which would do nothing, as "no sanitizers" it the default) of `ON` (which would enable all the sanitizers), as that seems to be what at least some other projects (not that it's mentioned anywhere I can see as a common convention), waiting for that to be released in a libpcap dot-dot release, and then changing "libpcap-1.10.1" to "libpcap-1.10.5" or whatever the release is that has that change.  (Don't change it *now*, as there isn't a 1.10.5 release yet.)

**Comment by Leaf550** [comment]
Oh, I see. There is a `ENABLE_SANITIZERS=OFF` in the `Cache variables` settings. But how can I remove this? It seems that CLion passed it automatically and "helpfully"😂.

**Comment by infrastation** [comment]
How do CLIon developers explain this behaviour?

**Comment by Leaf550** [comment]
Here are some relevant instructions I can found: [CLion Document](https://www.jetbrains.com/help/clion/cmake-profile.html#cmake-cache-variables)
But they didn't say how to disable these settings of CMake options.

**Comment by infrastation** [comment]
But you didn't ask. Try asking.

**Comment by guyharris** [comment]
> There is a `ENABLE_SANITIZERS=OFF` in the `Cache variables settings`. But how can I remove this?

Can you select that entry in the settings and then delete it?
