### ISSUE TITLE
IBM POWER7 Aix7.1, pcap timeout is invalid 

### ISSUE THREAD

**Issue by 1261385937** [the-tcpdump-group/libpcap#1242]
Here is the system information.
```bash
System Model: IBM,8202-E4D
Machine Serial Number: 06A60CT
Processor Type: PowerPC_POWER7
Processor Implementation Mode: POWER 7
Processor Version: PV_7_Compat
Number Of Processors: 8
Processor Clock Speed: 3612 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
LPAR Info: 1 06-A60CT
Memory Size: 31488 MB
Good Memory Size: 31488 MB
Platform Firmware level: AL770_112
Firmware Version: IBM,AL770_112
Console Login: enable
Auto Restart: true
Full Core: false
NX Crypto Acceleration: Capable and Enabled
 
Network Information
        Host Name: localhost
        IP Address: 172.16.61.250
        Sub Netmask: 255.255.255.0
        Gateway: 172.16.61.1
        Name Server: 
        Domain Name: 
 
Paging Space Information
        Total Paging Space: 4096MB
        Percent Used: 0%
 
Volume Groups Information
============================================================================== 
Active VGs
============================================================================== 
rootvg:
PV_NAME           PV STATE          TOTAL PPs   FREE PPs    FREE DISTRIBUTION
hdisk0            active            558         168         56..00..00..00..112
============================================================================== 

```

There is no ZEROCOPY_BPF, so  libpcap use read.
```c
#ifdef HAVE_ZEROCOPY_BPF
		if (pb->zerocopy) {
			if (p->buffer != NULL)
				pcap_ack_zbuf(p);
			i = pcap_next_zbuf(p, &cc);
			if (i == 0) {
				printf("pcap_next_zbuf i is 0\n");
				goto again;
			}
				
			if (i < 0)
				return (PCAP_ERROR);
		} else
#endif
		{
			printf("try to read\n");
			cc = (int)read(p->fd, p->buffer, p->bufsize);
			printf("read data size:%d\n", cc);
		}
```

It seems that BIOCIMMEDIATE is invalid, timeout is bad.  The read function will block all the time if  no packet arrived. 
I can not stop capture  if  no packet arrived. 
How can i solve this ? Thanks

**Comment by guyharris** [comment]
> It seems that BIOCIMMEDIATE is invalid, timeout is bad. The read function will block all the time if no packet arrived.
> ...
> How can i solve this ?

You might try complaining to IBM, who claim that 1) BIOCIMMEDIATE works and 2) BIOCSRTIMEOUT works in [their documentation for BPF devices](https://www.ibm.com/docs/en/aix/7.1?topic=capture-ioctl-bpf-control-operations); those are the ioctls that tcpdump.org's libpcap uses and that IBM's own libpcap uses.

If IBM's BPF devices don't work as documented, we would have to find out, somehow, the way to get timeouts and immediate mode to work.  Either IBM would have to fix their documentation, or we would need to be able to experiment on an AIX machine to try to figure out how their BPF devices work (that would require root access in order to capture traffic).

(This is not a characteristic of `pcap_next_ex()`, which is just a wrapper around `pcap_loop()`/`pcap_dispatch()`; this is a characteristic of IBM's BPF devices and the way they work.)

**Comment by infrastation** [comment]
Does the problem reproduce using AIX libpcap, upstream libpcap or both? Which particular versions?

**Comment by 1261385937** [comment]
The libpcap (1.10.1) is from this repository.  I compile it on AIX7.1 by 
```bash
./configure --disable-dbus --disable-shared CFLAGS=" -maix64" AR="ar -X64"
```
The AIX libpcap work bad, it will crash in  libpcap.a 😢 
@infrastation @guyharris

**Comment by infrastation** [comment]
Thank you for confirming, please re-test with 1.10.4, which includes almost two years of bug fixes after 1.10.1.

**Comment by 1261385937** [comment]
The crash has nothing to do with tcpdump. 😄 
With same code, the program works well if link our libpcap. But it will crash when link AIX's libpcap.
I have not get the AIX's libpcap source, so i do not know the detail about the crash.
@guyharris

**Comment by infrastation** [comment]
Please provide the additional information or this request will be closed.
