### ISSUE TITLE
How do I get the destination Mac when capturing "any" from multiple interfaces

### ISSUE THREAD

**Issue by LightCodeStack** [the-tcpdump-group/libpcap#1248]
When we capture a packet using “any” device, the SLL2 format only has the source address, so how do I get the destination address？Wireshark seems to have this problem as well.

**Comment by guyharris** [comment]
> how do I get the destination address?

One way to do this would be to modify the Linux kernel so that:

1. the `struct header_ops` structure, as defined in include/linux/netdevice.h, has a `parse_destaddr()` routine that, when called, extracts the destination address from the link-layer header, and define a new `static inline` function, `dev_parse_destaddr_header()`, in that include file, that calls that routine (see `dev_parse_header()` as an example);
2. modify all places that set the `header_ops` member of a `struct net_device` structure, as defined in include/linux/netdevice.h, so that they provide such a routine (the good news is that you don't have to modify every device driver, just all the files that defined a `header_ops` structure for a particular link-layer type);
3. define a new `TPACKET_V4` type in include/uapi/linux/if_packet.h;
4. modify the `tpacket_recv()` code path in net/packet/af_packet.c so that, for `TPACKET_V4`, they use`dev_parse_destaddr_header()` to extract the destination address and put it into the buffer along with other items such as the source address;
5. define a new link-layer type, `LINKTYPE_LINUX_SLL3`/`DLT_LINUX_SLL3`, with a header that includes the destination address, and modify libpcap to implement that by using `TPACKET_V4`;
6. modify all programs where you want to see the destination address (tcpdump, Wireshark, etc.) to default to `DLT_LINUX_SLL3` for the "any" device and to understand `LINKTYPE_LINUX_SLL3`/`DLT_LINUX_SLL3`.

Another way, which doesn't involve modifications to the Linux kernel, would be to modify libpcap - and, depending on how that modification is done, tools that use libpcap - not to capture in "cooked" mode on the "any" device, so that the capture gets the raw packet header *for link-layer types where that's available* (it may not be available for PPP - which, to be fair, doesn't normally have source and destination link-layer addresses unless 1) [HDLC-like framing](https://datatracker.ietf.org/doc/html/rfc1662) is used and 2) addresses other than 0xff are used, but I don't know whether that ever happens).

That doesn't work too well with pcap files, as they support only one link-layer type per file, and there's no guarantee that all "any" devices have the same link-layer type, and a solution other than a personal hack (meaning any solution that would become part of standard libpcap) would have to, somehow, deal with that case.

A workaround would be to define another link-layer header type, in which the packet data beings with a 4-byte Linux ARPHRD_ value (in either big-endian or little-endian order, so that we don't have to throw more byte-swapping pain into both libpcap's and Wireshark's code to read pcap and pcapng files), followed by the raw packet data, and then:

1. modify libpcap so that a filter expression is compiled into code that tests the ARPHRD_ type for the packet and then, based on that value, does the filter tests (for link-layer header values, IP header values, TCP/UDP header values, etc.) as appropriate for that particular link-layer type;
2. modify programs that capture packets or read pcap files (tcpdump, Wireshark, etc.) to understand this new link-layer header type, so that the code for that link-layer type looks at the ARPHRD_ type and then hands the data following the ARPHRD_ type to the dissector for the appropriate real link-layer type.

Alternatively, you could modify libpcap to support providing data to programs in a more pcapng-like fashion, and to support reading pcapng files with that mechanism for providing data and to support writing pcapng files, and, for the "any" device, provide the data in that fashion, so that, instead of the capture having a single fake "any" device with an SLL link-layer type, there would be interface data (a pcapng [Interface Description Block](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcapng.html#name-interface-description-block)) for each of the interfaces that provide packets.  This would mean that libpcap, when capturing on the "any" device, would have to keep track of all the interfaces that it had seen and, for each packet, check whether it's seen the interface on which it arrived and:

1. if so, provide the packet as an [Enhanced Packet Block](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcapng.html#name-interface-description-block), with the interface ID for the interface on which the packet arrived;
2. if not, look up the interface, provide a new Interface Description Block for the interface, and then provide the packet as an Enhanced Packet Block, with the interface ID for that new interface.

Note that interface IDs are **_NOT_** the same as interface indices as provided by the Linux kernel when capturing on a PF_PACKET socket; the interface ID of an interface is just the ordinal number of that interface in the set of Interface Description Blocks, with the first interface having an ordinal number of 0.  Therefore, libpcap would maintain a map between interface indices and interface IDs.

tcpdump, and other programs that don't know about pcapng files, would then have to be modified to handle the new APIs in libpcap to do pcapng-style capturing and pcapng-style reading of capture files.  (The new mechanism for providing pcapng-style information would also support pcap files, with a fake Section Header Block and an Interface Description block for one interface being provided, and with all packets being provided as Enhanced Packet Blocks for that one interface.)

If, however, you only need to capture packets on interfaces for which Ethernet link-layer headers are provided - which includes, obviously, Ethernet interfaces, as well as loopback interfaces and 802.11 interfaces *if you're not capturing in monitor mode* - a simpler mechansm would be to add a new "anyeth" device, which means "capture on all devices that provide Ethernet link-layer headers and don't show me any packets from other devices".

*That* could be implemented by:

1. define a new link-layer type, `LINKTYPE_ANYETH`/`DLT_ANYETH`, which has a 4-byte interface index in either big-endian or little-endian order (again, so we don't have to show more byte-swapping pain into libpcap) followed by an Ethernet header as the link-layer header, and having the "anyeth" device provide that link-layer header type;
2. having the receive path in Linux , for `DLT_ANYETH`, check the ARPHRD_ type of the packet and ignore it if it's not `ARPHRD_ETHER`, otherwise provide the packet to the caller;
3. have libpcap's packet-filter compiler treat `DLT_ANYETH` like `DLT_EN10MB`.

> Wireshark seems to have this problem as well.

Wireshark uses libpcap to capture packets, so it doesn't have any magic that would allow it *not* to have the problem.

**Comment by LightCodeStack** [comment]
I tried to change the kernel to put the destination address into the packet payload(add 6 bytes at beginning), but the ICMP packet would fail and the last 6 bytes of the icmp packet would be overwritten. However, the capture of udp and arp packets is normal.
