### ISSUE TITLE
Do not parse because of Mulit interface description block's linktype is different

### ISSUE THREAD

**Issue by InterNALXz** [the-tcpdump-group/libpcap#1252]
When I parse the attached file, the pcap_next_ex function will report an error, and when debugging, I find that the linktype and snapshot are inconsistent due to the mulit of headers in the packet. When I update p->linkType and p->snapshot in sf-pcapng.c:1256 and sf-pcapng.c:1268, the packets are parsed normally. Whether my behavior is an anomaly, or if validation of the first two is not necessary and does not require the introduction of errors. I'm pulling code from the master branch.
[Print.zip](https://github.com/the-tcpdump-group/libpcap/files/13783090/Print.zip)

**Comment by guyharris** [comment]
The current libpcap API is not capable of supporting pcapng files in which different interfaces have different link-layer types.

In order to dissect a packet, the dissecting code *must* know the link-layer type of the packet.  Libpcap does not have a call to get the link-layer type of a given packet; it only has a call, `pcap_datalink()` to get the link-layer type of the file.

That works for [pcap files](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcap.html), where there is only one link-layer type that is in [the header of the file](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcap.html#name-file-header).

That does not work for arbitrary [pcapng files](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcapng.html), where the file can have one or more [Interface Description Blocks](https://ietf-opsawg-wg.github.io/draft-ietf-opsawg-pcap/draft-ietf-opsawg-pcapng.html#name-interface-description-block), with different link-layer types, and packets may come from different interfaces and thus could have different link-layer types.

Libpcap attempts to support reading pcapng files as best it can, which means that `pcap_datalink()` returns the link-layer type for the *first* interface.  If other interfaces have the same link-layer type, that works; however, if an interface with a different link-layer type is seen, the program using libpcap will not be able to determine the link-layer type for packets on that interface, so libpcap reports an error.

Your capture file has four interfaces that provide IEEE 802.3br mPackets and two interfaces that provide regular Ethernet packets; the mPackets begin with a copy of the Ethernet preamble, not with the Ethernet destination address, so code that processes Ethernet packets will *not* correctly process mPackets.

I.e., if your code processes Ethernet packets, it will ***NOT*** process, for example, packet 42 in that capture file.  It begins with 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0xd5, which is *not* the destination MAC address and the first two bytes of the source MAC address, it's 7 bytes of preamble (0x55) followed by one byte of "Start mPacket Delimiter" with the value of 0xd5.  The "Start mPacket Delimiter" value of 0xd5, meaning that the packet is either an express packet, a complete preemptable packet or an initial fragment of a packet.  What follows those 8 bytes is the Ethernet header.

So what you're trying to do is not currently supported by libpcap.  A future version of libpcap may, using *different* APIs, support this, but you would have to modify your code to use the new APIs.  Furthermore, you will also have to add support for parsing packets with a link-layer type of `DLT_ETHERNET_MPACKET`, after reading enough of IEEE Standard 802.3br-2016, or clause 99 "MAC Merge sublayer" of IEEE Standard 802.3-2022 to know what to do with those packets.

(If you don't have time to read the MAC merge sublayer stuff, you might be able to get away with just checking for `DLT_ETHERNET_MPACKET` packed that begin with 0x55 0x55 0x55 0x55 0x55 0x55 0x55 0xd5, discarding packets that don't, and then skipping forward 8 bytes and parsing the packet under the assumption that the last 4 bytes, *if present* (check both the length and the captured length; it's the last 4 bytes of the length - if the captured length is less than the length, some or all of the CRC might be cut off by the captured length), are the CRC, not part of the packet data.  That won't handle packet preemption if it occurs, however.)

**Comment by guyharris** [comment]
Duplicate of #1321
