### ISSUE TITLE
haiku: Some warning should be fixed

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#1274]
Reference at:

https://github.com/the-tcpdump-group/libpcap/blob/6735956299c5fbc803255a14fa493886e3cf81c6/build.sh#L71
```
    # pcap-haiku.c:82:26: error: implicit conversion loses integer precision:
    #   'ssize_t' (aka 'long') to 'int32_t' (aka 'int')
    #   [-Werror,-Wshorten-64-to-32]
    # pcap-haiku.c:88:51: error: implicit conversion loses integer precision:
    #   'ssize_t' (aka 'long') to 'u_int' (aka 'unsigned int')
    #   [-Werror,-Wshorten-64-to-32]
    # pcap-haiku.c:98:15: error: implicit conversion loses integer precision:
    #   'ssize_t' (aka 'long') to 'bpf_u_int32' (aka 'unsigned int')
    #   [-Werror,-Wshorten-64-to-32]
```

**Comment by fxlb** [comment]
Cc @davidkaroly

**Comment by infrastation** [comment]
I am making some improvements to this file now, so I will try to have a look.

**Comment by fxlb** [comment]
@korli Any ideas ?

**Comment by infrastation** [comment]
The matter is, `recvfrom()` returns a 64-bit result and libpcap uses 32-bit types to store the various lengths. To me it would seem most reasonable to verify that `bytesReceived` does not exceed `handle->bufsize`, which is 32-bit. If that holds, then `bytesReceived` can be safely cast to a 32-bit type, otherwise something is wrong so it would be safest to drop the packet.

I was going to fix lengths in the `pcapint_filter()` invocation, so can make the build warning-free in the same go.

**Comment by guyharris** [comment]
> If that holds, then bytesReceived can be safely cast to a 32-bit type, otherwise something is wrong so it would be safest to drop the packet.

I was thinking the same thing.

**Comment by infrastation** [comment]
The warnings in `pcap-bpf.c` from Clang on Solaris look very similar (line numbers in `build.sh` are off after the code churn).

**Comment by infrastation** [comment]
The solution is ready, I am going to commit it after merging #1278.

**Comment by infrastation** [comment]
It seems #1278 is delayed due to lack of the snapshot, so this bug fix goes first. Commit 537976e addresses these warnings.
