### ISSUE TITLE
configure:3855: gcc -V >&5 gcc: error: unrecognized command line option '-V'

### ISSUE THREAD

**Issue by mozhengliang** [the-tcpdump-group/libpcap#1277]
To report a security issue please send an e-mail to security@tcpdump.org.

To report bugs and other problems, contribute patches, request a
feature, provide generic feedback etc please see the file
CONTRIBUTING.md in the libpcap source tree root.

**Comment by mozhengliang** [comment]
gcc version is too high, how to compile without lowering the version

**Comment by infrastation** [comment]
Please look through at least the first page worth of `CONTRIBUTING.md` and state the problem better.

**Comment by guyharris** [comment]
What do the commands

    gcc --version
    gcc -v
    gcc -V
    gcc -qversion

print on your machine?

**Comment by guyharris** [comment]
And what does the configure script print *to the standard output and error* - ***NOT*** to the config.log file! - when you run it?  Does it print any errors, or does it succeed?  If it succeeds, what happens if you run make?

**Comment by mozhengliang** [comment]
The problem is that I want to compile an arm-phytec-linux program on a linux VM. When I run the configure, I got error:&nbsp; unrecognized command line option '-V'.
Please see attached for more details






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月17日(星期六) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] configure:3855: gcc -V &gt;&amp;5 gcc: error: unrecognized command line option '-V' (Issue #1277)





 
And what does the configure script print to the standard output and error - NOT to the config.log file! - when you run it?  Does it print any errors, or does it succeed?  If it succeeds, what happens if you run make?

**Comment by guyharris** [comment]
> Please see attached for more details

All I see in the attached is a mixture of Chinese text, English text, and random stuff with asterisks and @ signs.

If I paste that into Google Translate, I get

> Sender: "the-tcpdump-group/libpcap" ***@***.***&gt;;
> Sent time: February 17, 2024 (Saturday) 7:37 pm
> ***@***.***&gt;;
> ***@***.******@***.***&gt;;
> theme:

which looks like text from a mail message; it doesn't give the information I want, which is what is printed by the configure script, as I asked when I said

> And what does the configure script print to the standard output and error - NOT to the config.log file! - when you run it?  Does it print any errors, or does it succeed?  If it succeeds, what happens if you run make?

Without that information, we will not be able to help you, and you will not be able to compile libpcap for your target.

**Comment by guyharris** [comment]
Does the configure script report "error: C compiler cannot create executables"?

If so, if you look in "config.log" for that error - ***NOT*** for the "unrecognized command line option" message! - what do you see in the lines before it, between "checking whether the C compiler works" and "error: C compiler cannot create executables"?

**Comment by mozhengliang** [comment]
error in config.log
please&nbsp;check out the attachment for more details







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月19日(星期一) 晚上6:22
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] configure:3855: gcc -V &gt;&amp;5 gcc: error: unrecognized command line option '-V' (Issue #1277)





 
Does the configure script report "error: C compiler cannot create executables"?
 
If so, if you look in "config.log" for that error - NOT for the "unrecognized command line option" message! - what do you see in the lines before it, between "checking whether the C compiler works" and "error: C compiler cannot create executables"?

**Comment by infrastation** [comment]
You mention attachments, but you do not actually attach actual attachments to the actual bug report. Please open https://github.com/the-tcpdump-group/libpcap/issues/1277 and see and make it good. Also please answer the other questions you have received.

**Comment by mozhengliang** [comment]
#1227 is an old problem, attached is my latest problem, these errors were reported in configure




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "the-tcpdump-group/libpcap"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年2月20日(星期二) 晚上6:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [the-tcpdump-group/libpcap] configure:3855: gcc -V &gt;&amp;5 gcc: error: unrecognized command line option '-V' (Issue #1277)





 
You mention attachments, but you do not actually attach actual attachments to the actual bug report. Please open #1277 and see and make it good. Also please answer the other questions you have received.

**Comment by infrastation** [comment]
Closing as spam.

**Comment by guyharris** [comment]
> these errors were reported in configure

No, those were reported in config.log.

The way configure scripts work is that they make various tests to figure out characteristics of the environment in which you're building the software.  Sometimes the only way to do that is to try something and see whether it succeeds or fails; very often, ***REGARDLESS*** of whether it succeeds or fails, the configure script can continue, and doesn't need to report a problem and stop.

In this particular case, the configure script is trying to get version information from the C compiler being used.  Different compilers have different command-line flags for reporting the version; the configure script does not know what compiler is being used, so it has to try several different flags.  Even if *none* of the flags work, the configure script can continue - it just can't report version information.

So that particular message is ***NOT*** an error that's of any interest.

If the configure script is ***FAILING***, that's an error.  If so, then the configure script will print an error message to its output; there's no need to look for it in config.log.  config.log is useful only for ***DEBUGGING*** purposes, if the configure script isn't doing what it's supposed to be doing.

We will just close bugs that report error messages from config.log that don't show what the ***REAL*** problem is, i.e. that don't show an error message printed by the configure script (not just logged to config.log), or don't say "the configure script failed to find some library that's on the system", or something such as that.
