### ISSUE TITLE
Why not  justifying Linux Kernel Version Dynamically for chosing pcap_read_linux_mmap_v1, or pcap_read_linux_mmap_vN

### ISSUE THREAD

**Issue by ShiverZm** [the-tcpdump-group/libpcap#1400]
I see the interface of "pcap_read_linux_mmap_vn" which controlled by Macro when compiling, and when i use a low Kernel compiling, and run my program, then the  Linux of higher Kernel still run pcap_read_linux_mmap_v1, so there is a question, why not use code to control use whichi version interface of pcap_read_linux_mmap?

**Comment by guyharris** [comment]
> I see the interface of "pcap_read_linux_mmap_vn" which controlled by Macro when compiling,

That's done because neither the `#define` for the newer versions of TPACKET nor the data structures the newer versions use are available in the system header files for systems with older Linux kernels.

> and when i use a low Kernel compiling,

Don't do that.  We won't support building on a system with an older kernel and using features not supported by that older kernel; it would require copying a bunch of Linux data structures and #defines to our own code, and that would be more of a maintenance effort than we want to do.

We've even dropped support for TPACKET_V1 in libpcap 1.10.

> and run my program, then the Linux of higher Kernel still run pcap_read_linux_mmap_v1, so there is a question, why not use code to control use whichi version interface of pcap_read_linux_mmap?

That's exactly what we do *IF* you're compiling on a system with a newer kernel; the resulting code can work with *older* kernels.

**Comment by ShiverZm** [comment]
i have to compile with older Kernels in old system like centos 5.10, because our program need compatible with low systems, and we just provider only one version of our program (it is unbelivable even i think),

**Comment by guyharris** [comment]
Then you will have to modify pcap-linux.c in such a fashion that it can be compiled on older systems, and maintain your modifications yourself.
