### ISSUE TITLE
[Patch] Improve IPv6 protocol filtering for fragmented packets

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#259]
Converted from [SourceForge issue 3401638](http://sourceforge.net/support/tracker.php?aid=3401638), submitted by msekletar

Tcpdump is unable to capture all icmp6 packets because of in-kernel filtering by Linux Socket Filter. If filter is set to icmp6, you will get output only for non-fragmented packets. When fragmentation on source site takes place(because of link mtu), tcpdump is unable to capture and process these packets, they are filtered out by kernel. It appears that kernel only check Next Header field in IPv6 header, in the case which original packet is fragmented to multiple packet's Next Header field is not icmp6 but has value IPv6 Fragment 0x2c.
Solution to this issue is to silently replace simple icmp6 filter with more sophisticated  filter, so user will get the expected output without knowledge of ipv6 header field's or advanced BPF syntax.

**Comment by brianjmurrell** [comment]
Does this mean that if I am using a libpcap filter of:

```
ether host ... and port 1234
```

I should see (udp) port 1234 IPv6 traffic, even if the packets on it are fragmented?

**Comment by mcr** [comment]
Brian J. Murrell <notifications@github.com> wrote:
    > Does this mean that if I am using a libpcap filter of:

    > ether host ... and port 1234

    > I should see (udp) port 1234 IPv6 traffic, even if the packets on it
    > are fragmented?

No, you will only see the fragment that has the UDP header in it.
The rest will not match the port filter.

There are other tools (wireshark/tshark) that, I think, can optionally
assemble fragments "online" for you before applying a filter.  
That means capturing all traffic from that ether host though.

There are other tools that can do this offline from a pcap file.
(I can't think of the right ones right now though)

-- 
]               Never tell me the odds!                 | ipv6 mesh networks [ 
]   Michael Richardson, Sandelman Software Works        | network architect  [ 
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by brianjmurrell** [comment]
Hi @mcr.  You probably don't recall, but our paths have crossed (a long time ago) in the past, IIRC, in regard to *SWAN.

> There are other tools (wireshark/tshark) that, I think, can optionally
assemble fragments "online" for you before applying a filter.
That means capturing all traffic from that ether host though.

Indeed.  Which can mean having to capture a haystack to assemble a needle from it.  That's what I was trying to avoid since I want to capture over (relatively) long time periods.

The amount of total traffic from a host can be overwhelming compared to just the traffic I want to see, which can, unfortunately include fragmented IPv6 packets.  :-(

Would it be impossible for libpcap to do this for IPv6 now that fragmentation is done as an extension header?
