### ISSUE TITLE
[Feature] Function to obtain specific error codes

### ISSUE THREAD

**Issue by guyharris** [the-tcpdump-group/libpcap#286]
Converted from [SourceForge issue 3467212](http://sourceforge.net/support/tracker.php?aid=3467212), submitted by fernandogont

The libpcap I/O function return -1 on error, but it's not possible to obtain an error-specifc code, such that a program can act diferrent depending on each specific error condition.

A function like
int pcap_geterrcode(pcap_t *)
could return a platform-independent code that specifies the last error condition that ocurred.

**Comment by infrastation** [comment]
This request was made on 2011-12-30. By that time `pcap/pcap.h` already defined 11 error codes (revision 6eb6d5b):
```c
#define PCAP_ERROR                   -1      /* generic error code */
#define PCAP_ERROR_BREAK             -2      /* loop terminated by pcap_breakloop */
#define PCAP_ERROR_NOT_ACTIVATED     -3      /* the capture needs to be activated */
#define PCAP_ERROR_ACTIVATED         -4      /* the operation can't be performed on already activated captures */
#define PCAP_ERROR_NO_SUCH_DEVICE    -5      /* no such device exists */
#define PCAP_ERROR_RFMON_NOTSUP              -6      /* this device doesn't support rfmon (monitor) mode */
#define PCAP_ERROR_NOT_RFMON         -7      /* operation supported only in monitor mode */
#define PCAP_ERROR_PERM_DENIED               -8      /* no permission to open the device */
#define PCAP_ERROR_IFACE_NOT_UP              -9      /* interface isn't up */
#define PCAP_ERROR_CANTSET_TSTAMP_TYPE       -10     /* this device doesn't support setting the time stamp type */
#define PCAP_ERROR_PROMISC_PERM_DENIED       -11     /* you don't have permission to capture in promiscuous mode */
```
So at least in some instances it was possible to handle different causes of failure differently (which is a reasonable expectation) by examining the return value of the function of interest. Perhaps some instances still exist that return `PCAP_ERROR` instead of more specific error codes (existing or new). To improve that it would be necessary to explain the practical use case, which can be done through other requests as and when makes sense. Closing.

**Comment by guyharris** [comment]
Those error codes are returned by new APIs; the main remaining APIs where you'd want more specific error codes are the packet-reading APIs `pcap_dispatch()`/`pcap_loop()`/`pcap_next_ex()`.

If new APIs are added for reading packets, those should support more specific codes.

**Comment by infrastation** [comment]
Thank you for explaining. Would it be better to reopen this issue or to add this point to a list of things to fix in a future version of the API?

**Comment by infrastation** [comment]
It is on the list.
