### ISSUE TITLE
pcap-filter man page clarifications and improvements

### ISSUE THREAD

**Issue by cjmaynard** [the-tcpdump-group/libpcap#326]
The pcap-filter man page could benefit from some clarifications and improvements, such as:

1) proto qualifiers:  The man page reads, "proto qualifiers restrict the match to a particular protocol. Possible protos are: ether, fddi, tr, wlan, ip, ip6, arp, rarp, decnet, tcp and udp. "  However, as noted in the discussion from http://ask.wireshark.org/questions/26350/how-to-filter-wlan-with-a-capture-filter, the semantics of those proto qualifiers differ, in particular ether, fddi, tr and wlan from the others.  To quote Guy Harris, "The problem is that there are both proto qualifiers and protocol abbreviations, and some tokens, such as ip, ip6, tcp, and udp, serve both purposes".  Some clarification might therefore be beneficial to users.

2) Protocol Abbreviations:  The man page reads, "tcp, udp, icmp [are] Abbreviations for:  proto p where p is one of the above protocols. ".  icmp6 isn't listed.  Should it be?  Are there others that should be listed too?

3) sctp isn't documented anywhere.

4) expr relop expr: The man page reads, "Proto is one of ether, fddi, tr, wlan, ppp, slip, link, ip, arp, rarp, tcp, udp, icmp, ip6 or radio, ...", but ppp, slip, link, radio [and icmp6] aren't listed previously when describing the proto qualifiers (see point 1 above), and decnet is missing from this list.  It might also be nice if this was a sorted list of protos.

5) Speaking of a sorted list, it might be nicer if all the primitives were sorted to make it easier to find/reference them.

**Comment by infrastation** [comment]
> 3. sctp isn't documented anywhere.

Now it is. @cjmaynard or anybody else, would you like to address any other items on the list?

**Comment by infrastation** [comment]
After studying `gen_proto_abbrev_internal()` for some time I would like to suggest resolving point 2 of the original problem statement as follows:
* `pim` is a shorthand for `proto \pim`, `ah` is a shorthand for `proto \ah` and `esp` is a shorthand for `proto \esp`.
  
  This way, each of these three items expands to "(IPv4 or IPv6) and protocol X" (which is the meaning of `proto X`) and should be added as a valid abbreviation to the man page.
* `icmp` is a shorthand for `ip proto 1`. `icmp6` is a shorthand for `ip6 proto 58`. Both `proto \icmp` and `proto ipv6-icmp` expand (by the definition of `proto X`) to expressions that get either IPv4 ICMP or IPv6 ICMP6 wrong, so it is quite right that there are no shorthands that expand to these two expressions.
  
  This way, the man page text should be fixed: it incorrectly says that `icmp` expands into `proto \icmp`, this is not (and should not be) the actual behaviour. Likewise, `icmp6` is not on the list of abbreviations, so it should remain this way.
* `ip proto protocol` lists `icmp6` as a protocol name, which makes no sense for IPv4; `ip6 proto protocol` does not explain that in the list of protocols `icmp` makes no sense for IPv6. The list of protocols does not explain that all names are subject to a lookup using `getprotobyname()`, on my Linux host it means that ICMPv6 is known only as `ipv6-icmp` as that's how it appears in `/etc/protocols`.
  
  These two sections should be amended for clarity.

**Comment by infrastation** [comment]
Current progress: points 2 and 3 have been fully resolved, there is a bit of improvement towards points 4 and 5, point 1 still remains not reviewed. Would anybody like to progress any of the remaining work items?

**Comment by guyharris** [comment]
> The list of protocols does not explain that all names are subject to a lookup using `getprotobyname()`, on my Linux host it means that ICMPv6 is known only as `ipv6-icmp` as that's how it appears in `/etc/protocols`.

Not just Linux, probably universal for most if not all UN\*Xes:

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.6.4
BuildVersion:	20G417
$ egrep icmp /etc/protocols
icmp	1	ICMP		# internet control message protocol
ipv6-icmp	58	IPV6-ICMP	icmp6	# ICMP for IPv6
```

```
solaris11$ uname -sr
SunOS 5.11    # That's the core OS component of Solaris 11
solaris11$ egrep icmp /etc/protocols
icmp		1	ICMP		# internet control message protocol
ipv6-icmp	58	IPv6-ICMP	# IPv6 internet control message protocol
```

As neither AIX nor HP-UX, to name the two surviving non-Linux/non-BSD UN\*Xes, run on x86, I don't have a VM for them.  I didn't bother with the \*BSDs as macOS is a BSD cousin and they're probably all much the same.

And, as for our only non-UN\*X platform:

```
C:\Users\guy>find "icmp" C:\WINDOWS\system32\drivers\etc\protocol

---------- C:\WINDOWS\SYSTEM32\DRIVERS\ETC\PROTOCOL
icmp       1     ICMP         # Internet control message protocol
ipv6-icmp  58    IPv6-ICMP    # ICMP for IPv6
```

(yeah, that's how you say "grep" - sort of, except that it's a string match, and you *have* to quote it, to let `find` know that it's a search string and not a path name - and `/etc/protocols` on Windows).

So it's going to be "ipv6-icmp" if you want "Internet Control Message Protocol (ICMPv6) for the Internet Protocol Version 6 (IPv6)", as RFC 4443 calls it.  But since the RFC calls it "ICMPv6", maybe we should offer "icmpv6" as an alias for "ipv6-icmp".

**Comment by infrastation** [comment]
Thank you for the additional information. "icmp6" is probably a legacy name since macOS lists it as an alias (FreeBSD does too, but NetBSD and OpenBSD don't). AIX 7.1 and 7.2 have the following:
```
icmp            1               ICMP                    #Internet Control Message              [RFC792]
ipv6-icmp       58              IPv6-ICMP               #ICMP for IPv6                   [RFC1883]
```
Re "icmpv6" or a similar addition, after looking into this part of the man page for a while it is difficult for me to tell right now whether adding it into the existing syntax will make it easier to comprehend.

**Comment by cjmaynard** [comment]
Maybe it would be helpful to document "**proto** protocol" more similarly to how "**ip proto** protocol" is documented?

And then instead of explicitly listing ah, esp, pim, sctp, tcp udp as abbreviations for "**proto** \protocol", perhaps just list them as _examples_ of the above syntax, because at least on my Windows system, ggp, egp, pup, hmp, xns-idp, rdp, ipv6, ipv6-route, ipv6-frag, ipv6-icmp, ipv6-nonxt, ipv6-opts and rvd would all work as well, but naturally that list will differ between platforms. 
 Of course if there are aliases, such as the proposed `icmpv6`, then those would need to be explicitly documented since they won't appear in the `/etc/protocols` (or `C:\Windows\System32\drivers\etc\protocol`) file.

**Comment by infrastation** [comment]
Thank you for the additional input. The man page includes 6 uses of "protocol" in the sense of (and involving a lookup in) `/etc/protocols`:
* `ip proto protocol`
* `ip6 proto protocol`
* `proto protocol`
* `ip6 protochain protocol`
* `ip protochain protocol`
* `protochain protocol`

The first one already explains what it means, and subsequent ones could say "protocol (as explained in "ip proto protocol" above)" or some such, would that clarify the meaning?

Considering the other point, please note that `tcpdump 'sctp'` works because it is a shorthand for `tcpdump 'proto \sctp'`, which also works, but `tcpdump 'rvd'` or `tcpdump 'hmp'` should not work because there is no such abbreviation, even if the entries are in the file; however, `tcpdump 'proto rvd'` and `tcpdump 'proto hmp'` would work so long as the entries are in the file. Is this consistent with the behaviour you are observing?

**Comment by cjmaynard** [comment]
Yes, that's the behaviour I'm seeing.  But the documentation for `proto protocol` seems to imply that only ah, esp, pim, sctp, tcp or udp can be used when specifying the protocol in `proto \protocol`, does it not?  And now that you mention it, I think `ip6 proto protocol` could also use some clarifications, akin to `ip proto protocol`.

And another observation: It seems that for ah, esp, pim, sctp, tcp and udp, a filter of "foo" is not the same as a filter of "proto \foo".  The former tests for IPv6 first and IPv4 second, while the latter tests in the opposite order.  Why is that?  Shouldn't they be identical?

**Comment by infrastation** [comment]
The text does not mean that, but it is possible to see how it can be understood this way. I guess the reference to "protocol" meaning will help to clarify that a bit more.

Commit c93c8ff very recently made `foo` and `proto \foo` identical bytecode-wise (they were not identical, but equivalent, as far as I managed to establish).

**Comment by infrastation** [comment]
Commit ffa313d progresses point 4. However, I do not currently see a nice way to coordinate it with point 1 (the list of proto qualifiers at the top) at this time. Perhaps saying something like `indexproto [ expr : size ]` for index operations would be better because not all protocol tokens support the index operation (there is a default case in `gen_load_internal()`).

**Comment by infrastation** [comment]
Current status, in terms of the points made in the original problem statement, is as follows.

Point 1 looks addressed as far as is reasonably practicable: the man page has been updated several times to expand protocol abbreviations better and to mention more tokens the are also keywords/abbreviations and must be escaped.

Points 2-5 look fully resolved via the associated commits (often explained in the comments).

Hence closing this request as resolved, thank you everyone for your input and patience. If you spot any other space for improvement in future, please prepare the changes and open a pull request.
