### ISSUE TITLE
pcap-inject - wrong Mac address

### ISSUE THREAD

**Issue by cairn1** [the-tcpdump-group/libpcap#341]
I am using a device to relay packets between networks, I am using libpcap to capture the packets, do some processing, then sending to another device, I then pcap_inject to send the packet onwards, the problem is that the mac address of the intermediary device is being placed in the packet. In the pcap man pages it warns of this. Looking at the pcap source I see send() API is being called but from that point I am getting lost. This work is on Linux and I will be able to update the kernel as required, but does anybody know where I need to start?

**Comment by infrastation** [comment]
Is there any outstanding problem that remains to be solved here?

**Comment by guyharris** [comment]
On an Ubuntu 20.04 VM with a 5.11.0 kernel, a small test program I wrote that sends a packet with `pcap_inject()` and uses a source MAC address specified on the command line appears to cause the packet to appear on the "wire" with the specified source MAC address.

(I say "wire" because I tested this by sending the packet as a broadcast and capturing on the bridge101 interface on the host; that's the interface on which traffic from the guest appears, so the "wire" exists entirely in software.  Perhaps that won't work on a *real* machine on a *real* Ethernet, but I suspect it will work.)

This won't work with a cooked-mode capture, but there's no reason to *expect* it to work with a cooked-mode capture.

So...

> Is there any outstanding problem that remains to be solved here?

I'd say the answer is "no".

**Comment by infrastation** [comment]
Thank you for confirming. I can run the test program on hardware with real wire if you wish.

**Comment by guyharris** [comment]
If you want to try it.  Here it is:

[pcap-arp.c.txt](https://github.com/the-tcpdump-group/libpcap/files/7530630/pcap-arp.c.txt)

(stupid extra .txt required by GitHub).

**Comment by infrastation** [comment]
Thank you, it works: I specify an arbitrary source MAC address on one Linux computer (AMD64 kernel 5.11.0) and another sees the address in the incoming packet.
