### ISSUE TITLE
pcap_stats() shows always 0 on nf* interfaces on linux

### ISSUE THREAD

**Issue by crondaemon** [the-tcpdump-group/libpcap#412]
When calling pcap_stats() on nf interfaces (nflog, nfqueue) on Linux, ps_recv is always 0.

Example code: https://gist.github.com/crondaemon/ec4ebd6d3e577aac9dd5

On eth0: working. On nflog: not working.

**Comment by guyharris** [comment]
To quote the `pcap_stats()` man page:

> Both ps_recv and ps_drop might, or might not, count packets not yet read from the operating system  and thus not yet seen by the application.

For nf interfaces, it doesn't count packets not yet read from the operating system, and the sample code just runs without reading packets.  Unless there's some way of asking a netfilter socket how many messages have been processed in the kernel since the socket was opened, it would be completely impossible for libpcap to count packets not read from the operating system.
