### ISSUE TITLE
how to design a multi-thread module to sniffer network traffic by libpcap

### ISSUE THREAD

**Issue by orange-jacky** [the-tcpdump-group/libpcap#428]
i read some libpcap manual, and most says to use pcap_next,pcap_loop,pcap_next_ex function etc.
and i barely read something about multi-thread to use libpcap. 

here i wanna design a multi-thread module to use libpcap, the first thread pool get packet by pcap_next or pcap_loop and get a packet to insert a packet queue. the second thread pool  read packet from packet queue and reassemble packet following tcp/ip stack, after reassembling a tcp flow, the tcp flow is inserted to a tcp flow queue. 

Is there anyone can send me some useful information about using libpcap whit a multi-thread module?
thanks to answers my issue.

**Comment by mcr** [comment]
I suggest you bring this up on the list, rather than github issue.

**Comment by orange-jacky** [comment]
i had sent email to mailing lists as the following steps.
"tcpdump-announce
This list is for announcements only. Subscribe by sending an e-mail to tcpdump-announce-request@lists.tcpdump.org with the phrase "subscribe tcpdump-announce" as body and subject. The most recent messages can be accessed from gmane. Old archives can be found here.

tcpdump-workers
This list is focused on development. It will also receive announcements, so one need only subscribe to one list or the other. Subscribe by sending an e-mail to tcpdump-workers-request@lists.tcpdump.org with the phrase "subscribe tcpdump-workers" as body and subject, or through the web interface. The most recent messages can be accessed from gmane. Old archives can be found here. Posts to this list must originate from the subscriber's address." 

and can you tell me  how to bring my question on the list?

with kind regards.

**Comment by orange-jacky** [comment]
i had added it to tcpdump-workers, thanks to your advice.

**Comment by emilio-aburto** [comment]
I know this issue is old, but I've been working on something that may help you.

https://github.com/niclabs/ratadns-speedy

**Comment by HaoQChen** [comment]
> I know this issue is old, but I've been working on something that may help you.
> 
> https://github.com/niclabs/ratadns-speedy

It is 404

**Comment by emilio-aburto** [comment]
I think it got merged into Fievel
[https://github.com](<a href=)/niclabs/ratadns-fievel">https://github.com/niclabs/ratadns-fievel

-------- Mensaje original --------
On 20 ago. 2019 12:39, HaoQChen < notifications@github.com> escribió:
I know this issue is old, but I've been working on something that may help you.
[https://github.com](<a href=)/niclabs/ratadns-speedy">https://github.com/niclabs/ratadns-speedy
It is 404
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[https://github.com](<a href=)/the-tcpdump-group/libpcap/issues/428?email_source=notifications">https://github.com/the-tcpdump-group/libpcap/issues/428?email_source=notifications\u0026email_token=AAL4IXGP22RGUQL57PNK67LQFQM3DA5CNFSM4BAJVIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4W5AFQ#issuecomment-523096086", "url": "[https://github.com](<a href=)/the-tcpdump-group/libpcap/issues/428?email_source=notifications">https://github.com/the-tcpdump-group/libpcap/issues/428?email_source=notifications\u0026email_token=AAL4IXGP22RGUQL57PNK67LQFQM3DA5CNFSM4BAJVIQKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD4W5AFQ#issuecomment-523096086", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by teoring** [comment]
Its 404 again :)
