### ISSUE TITLE
1.7.3 compile failure due to missing define on rhel 6.3/centos 6.4 

### ISSUE THREAD

**Issue by heasus** [the-tcpdump-group/libpcap#443]
--- pcap-linux.c.orig   2015-04-22 20:19:15.000000000 +0000
+++ pcap-linux.c
@@ -3482,7 +3482,7 @@ activate_new(pcap_t *handle)
         */
        handle->fd = sock_fd;
 
-#ifdef SO_BPF_EXTENSIONS
+#if defined(SO_BPF_EXTENSIONS) && defined(SKF_AD_VLAN_TAG_PRESENT)
        /*
         * Can we generate special code for VLAN checks?
         * (XXX - what if we need the special code but it's not supported

**Comment by guyharris** [comment]
So, according to the Wikipedia article on RHEL, RHEL 6.3 has a 2.6.32 kernel.  My 2.6.32.4 kernel source tree doesn't have SKF_AD_VLAN_TAG_PRESENT, but it also doesn't have SO_BPF_EXTENSIONS. SO_BPF_EXTENSIONS appears to have shown up at some point in the 3.x series.

So what kernel version are you running?  And what header defines SO_BPF_EXTENSIONS on your system?

**Comment by heasus** [comment]
2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64
x86_64 GNU/Linux

/usr/include/asm-generic/socket.h:#define SO_BPF_EXTENSIONS     48

and its not within any control structure (ifdef, etc)

**Comment by guyharris** [comment]
Sigh, I guess Red Hat have decided to Do Their Own Thing here.  I unpacked the CentOS 6.4 linux-2.6.32-358.el6 package, and the kernel source has neither SO_BPF_EXTENSIONS nor SKF_AD_VLAN_TAG_PRESENT anywhere in it, so I have *no* idea why they provide it in a header.

That means that they don't actually *support* SO_BPF_EXTENSIONS, so there's no point in trying to do anything with them.

Fixed in 3c2bd64e742c2d81346456fc8773425073717f61.

**Comment by msekletar** [comment]
This is weird, AFAIK kernel people were supposted to backport all patches needed on kernel side. I will double check because it seems like they messed up that backport. Or maybe newer z-stream kernel update is still stuck somewhere in the pipeline.

**Comment by msekletar** [comment]
Patches introducing SO_BPF_EXTENSIONS were backported for RHEL6 and released with RHEL-6.6.
