### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [the-tcpdump-group/libpcap#480]
I would like to point out that identifiers like "[`__pcap_atodn`](https://github.com/the-tcpdump-group/libpcap/blob/70d59795dca9c1b9ffaea88c3334ae3808152eda/nametoaddr.h#L38)" and "[`__PCAP_TC_H__`](https://github.com/the-tcpdump-group/libpcap/blob/93b13ef5b2140efd61af8684276d2ddc4ead3bf7/pcap-tc.h#L32)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by guyharris** [comment]
libpcap isn't written in C++, so, for headers and library routines not exported from the library, such as `__pcap_atodn` (an internal routine) and `__PCAP_TC_H__` (used in an internal header file), the C++ language standard isn't relevant.

I'll see whether there are any issues in *exported* routines and headers.

**Comment by elfring** [comment]
I recommend to [reconsider the usage of a few underscores in special identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") also for this software.

**Comment by guyharris** [comment]
Well, we aren't changing any exported identifiers, as that would break the API, and we're simply not going to do that, regardless of whether POSIX gets its knickers in a twist about us using XXX_t-style type names, for example.  What's done is done.

We'll worry about non-exported identifiers if they actually cause a problem when somebody builds libpcap.

**Comment by elfring** [comment]
How do you think about to avoid that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by guyharris** [comment]
If the only way to avoid that is to make incompatible API changes, I'd rather have the (probably low) risk of breakage due to undefined behavior than the *certain* risk of breaking existing code.  We're not going to rename `pcap_t` even if it ends with a Forbidden Suffix(TM).

As for the others, we've somehow managed to survive, so changing those isn't going to be a high priority on my task list.

**Comment by elfring** [comment]
Would you like to publicly restrict the safe usage of your software library for its application in implementations of the programming languages “C” and “C++”?

**Comment by guyharris** [comment]
libpcap isn't used "in implementations of the programming languages “C” and “C++”" - it's not part of any library specified by any of the standards for C or C++.

Do you mean "restrict the safe usage of your software library to use from code written in C and C++", "restrict the safe usage of your software library in C and C++ programs and libraries to environments that don't define symbols that begin with `pcap_`", or something else?

**Comment by mcr** [comment]
Markus Elfring <notifications@github.com> wrote:
    > Would you like to publicly restrict the safe usage of your software
    > library for its application in implementations of the programming
    > languages “C” and “C++”?

works for me.

--
]               Never tell me the odds!                 | ipv6 mesh networks [
]   Michael Richardson, Sandelman Software Works        | network architect  [
]     mcr@sandelman.ca  http://www.sandelman.ca/        |   ruby on rails    [

**Comment by elfring** [comment]
>libpcap isn't used "in implementations of the programming languages “C” and “C++”" - it's not part of any library specified by any of the standards for C or C++.

Thanks for this acknowledgement.

I recommend then again to take another look at [the standard rules for the usage of reserved identifiers](http://en.cppreference.com/w/cpp/language/identifiers#In_declarations "Description of rules for the identifier selection").
How do you think about to [reduce the tampering with the reserved name space](https://github.com/the-tcpdump-group/libpcap/blob/fb20696441656c36961e92e3ddf074d770e81c55/nametoaddr.h#L38 "Update candidate: __pcap_atodn()") a bit more?

**Comment by guyharris** [comment]
> How do you think about to reduce the tampering with the reserved name space a bit more?

I think it's a very low priority, given that, as the header file says:

     * Routines used for name-or-address-string-to-address resolution
     * that are *not* exported to code using libpcap.

If some version of libpcap happens to publish that header file, whoever produced that version has made a mistake.  *We* don't install that header; to quote the commit message for the commit that created that header:

    Remove some functions that are *not* marked as exported on Debian from
    pcap/namedb.h, putting them in a local nametoaddr.h header instead, and
    don't export them.

Libpcap 1.8.0 and later from tcpdump.org don't publish that header file and don't export the routines declared in it.

Ubuntu 17.04 doesn't publish that header file, doesn't declare those routines in any header file it publishes, and doesn't export the routines declared in it. (It comes with a libpcap based on 1.8.1.)

Probably most if not all Linux distributions and \*BSDs with 1.8.0-or-later libpcap behave the same.

macOS Sierra 10.12.5 doesn't publish that header file and doesn't declare those routines in any header file it publishes; it exports the routines declared in it, but that might just be because they don't know for certain that no application for macOS uses them.  (It comes with a libpcap based on 1.8.1.)

So changing the routine names would only affect the libpcap build process; programs built with libpcap don't see those routines.

**Comment by infrastation** [comment]
When proposing to make changes in libpcap exported interface to improve standard conformance, it helps to remember that libpcap release 0.0 was out on 21 June 1994 (23 years ago). In particular, the `pcap_t' typedef has been in the header file since then. So, first, this problem isn't actually new. Second, the team that maintains this code now did not originally write it.

Having considered your recommendations, which you have made more than once, we can agree that in the hindsight certain things could be done better. However, we are not obliged to make every possible improvement, which is good because we simply cannot make every possible improvement given the amount of resources we have. So those particular recommendations will likely remain not implemented for a while longer. Hopefully this will help to do some other work.

If you would like to help this project, please look through the list of open bugs and see if you can help to troubleshoot or resolve any of them.
