### ISSUE TITLE
Get a MAC Address from an interface

### ISSUE THREAD

**Issue by Marcsalv** [the-tcpdump-group/libpcap#487]
I´d like to know if there is some way to get the MAC Address (on Windows) from a pcap_if_t structure.

**Comment by guyharris** [comment]
No, there isn't.  There's currently no libpcap/WinPcap API to provide MAC addresses.

**Comment by Evils-Devils** [comment]
Is there any hope on getting this feature?
I was quite surprised to find out this is not provided as getting an interface's IP address is already possible.
I've got an application that is not portable just because of this
and i believe arp-scan manages it in a portable way (though under GPL).

**Comment by Evils-Devils** [comment]
bump @guyharris (tagged you in an edit above, not sure if you got notified)

**Comment by evils** [comment]
@guyharris @infrastation
I extracted `arp-scan`'s `get_hardware_address()` function to get an interface's MAC address on Linux, BSD and Solaris, and licensed it under BSD-3 (with permission) [here](https://gitlab.com/evils/get_hardware_address).
Perhaps this is of interest to you?

**Comment by infrastation** [comment]
Thank you for proposing this, please do not be offended by some constructive criticism of the proposed solution.

Are the authors of arp-scan fine with someone taking GPL code and declaring it BSD?

The proposed code seems to assume that hardware address length always equals to 6 bytes, there are cases when that is not true (typically longer than 6 bytes). Even if you do not feel like implementing this functionality in a generic way and covering each non-Ethernet edge case, it would be right if the new function (whether it becomes a part of libpcap or not) failed safe instead of copying just the first bytes of the hardware address or writing out of the provided buffer bounds. Also on Linux the right way to obtain network interface information would be through libnl or one of the libraries on top of it.

Plenty of bicycles have already been invented in this area, in  cross-platform way too, which is likely the reason libpcap never needed to go beyond the initial "list of addresses" model.

**Comment by evils** [comment]
@infrastation, I'm absolutely not offended, I'm happy to get any feedback at all :).
Yes, i definitely got [permission](https://github.com/royhills/arp-scan/issues/43) to changing the license to BSD (some discussion about libpcap there).
Yes, that code assumes 6 bytes, I get that that limitation is probably a deal breaker for something as universal as libpcap.
I have no illusion that the function I've extracted could be dropped into libpcap without significant change.
I'm merely bringing it to your attention in in hopes of providing someone a starting point, or even just present the option to anyone that makes it to this issue.

Right, changing the linux part to use netlink is the first item of the TODO list there, but I got distracted by other stuff...

I'm not aware of any other cross-platform ways of doing this that I could have used instead...
I'm not sure what you mean with "list of addresses", to my knowledge libpcap does not provide any way to get a list of hardware addresses for an interface (or just one of them).

I do think there's a need among libpcap users for this functionality
and as stated above, I was surprised it is not already included.
