### ISSUE TITLE
NULL pointer dereference in snf_platform_cleanup()

### ISSUE THREAD

**Issue by pgiffuni** [the-tcpdump-group/libpcap#490]
Hello;
There is a NULL pointer dereference in this line:

https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-snf.c#L67

In FreeBSD we (actually coccinelle) fixed it like this:
https://svnweb.freebsd.org/base?view=revision&revision=297983

**Comment by guyharris** [comment]
Fixed in 4418d041840c295df2ad6ac97459a3e460a8f3d4 by:

- ensuring that, if we call any of the cleanup routines internally, we don't pass the routine a null pointer (the call from `pcap_close()` won't happen if the argument to `pcap_close()` is null, as `pcap_close()` couldn't even *find* the cleanup routine if its argument is null);
-  *removing* the null argument checks from the cleanup routines.
