### ISSUE TITLE
Cannot open pcapng file

### ISSUE THREAD

**Issue by ujos** [the-tcpdump-group/libpcap#527]
Hello,

I have pcapng file which can be opened by both Wireshark 2.0.5 and WinPcap 4.1.3 (libpcap 1.7.3). But I cannot open this file using latest code in GIT Wpcap v4.1.4. 

`Unable to open the file 'sample_00000_20160915102311.pcapng'. Error: invalid interface capture length 4294967295, bigger than maximum of 262144`

WinPcap 4.1.3 Pcap v1.7.3 works but timestamps are not correct:
`printf("%ld:%ld (%ld)\n", header->ts.tv_sec, header->ts.tv_usec, header->len);`
prints:
`-1083806075:0 (558)`

Wiresharks opens file correctly.

If I convert this file into pcap with nanoseconds, Wpcap 4.1.4 (git) works.

[sample_00000_20160915102311.pcapng.zip](https://github.com/the-tcpdump-group/libpcap/files/490712/sample_00000_20160915102311.pcapng.zip)

**Comment by fxlb** [comment]
The header of this capture file is invalid. An interface capture length sanity check was added by  f983e075fbef40fe12323c4dd8f85c88eaf0f789. What is the origin of this capture file?

**Comment by ujos** [comment]
This file was collected on a Linux machine with a ProfiShark

**Comment by fxlb** [comment]
The vendor should be asked to set the good snaplen in the pcapng file. Do you try to contact Profitap support ?

**Comment by ujos** [comment]
No, I did not. This issue was raised by user of Winpcap 4.1.3 (libpcap 1.7.3) library. I will ask him to contact Profitap support. Thank you very much for prompt response!

**Comment by fxlb** [comment]
For the record, could you add a zip file with the original unconverted capture file?

**Comment by ujos** [comment]
Attached file on the top is original.

BTW, if file is wrong, how does Wireshark open it?

**Comment by fxlb** [comment]
Original ? capinfos prints "Capture application: Editcap 2.2.0" and "Time precision = nanoseconds". So I think it's the converted to nanoseconds file.

Wireshard uses its own function to read the file, not the libpcap one. This function is more permissive.

**Comment by guyharris** [comment]
Wireshark also imposes a maximum-packet-size limit; however, it allows packets to be bigger than the claimed snapshot length, expanding its buffer as necessary when the packet is read, *but* returns an error if the buffer size is too big.

libpcap doesn't do that because, to quote the comment in `sf-pcap.c`:

                 * XXX - we don't grow the buffer here because some
                 * program might assume that it will never get packets
                 * bigger than the snapshot length; for example, it might
                 * copy data from our buffer to a buffer of its own,
                 * allocated based on the return value of pcap_snapshot().

Wireshark doesn't have this issue because its library for reading capture files currently doesn't have a stable API, the Wireshark program don't make that assumption, and any third-party code that uses the library does so at its own risk.

Both libpcap and Wireshark impose a limit to prevent a file from causing the program to fill up the address space with a huge buffer and then fail.  That's less of an issue with ILP64 and LLP64, although there are more limits than just the address space size, so it could be an issue there as well.

What we could do in libpcap is, if the snapshot length is too large, just limit it to the maximum, and, if there actually *are* packets bigger than that, fail when we actually read them.

**Comment by guyharris** [comment]
2be9c29 should fix the "can't open" part - it will allow a snaplen in a pcap file or a pcapng IDB to be > MAXIMUM_SNAPLEN, but won't allocate a buffer that's too big, and, for pcapng files, will reject packets that won't fit in a maximum-sized buffer or that have a captured packet data length that exceeds the snaplen.

The time stamp part is probably a bug.  We don't produce WinPcap, and the WinPcap people never produced a WinPcap release based on pcap v1.7.3, so somebody else made "WinPcap 4.1.3 Pcap v1.7.3" - you should talk to them about the time stamp problem.

**Comment by wjt** [comment]
@guyharris any chance of a release of libpcap that contains this fix (2be9c29) and the related fix (1a6b088) to allocate a longer buffer for `DLT_DBUS` captures? I've been including [a Git snapshot of libpcap in the Bustle Flatpak](https://github.com/flathub/org.freedesktop.Bustle/blob/001366b782e7d51b67a09d6e5fa6ac9368d1bd79/org.freedesktop.Bustle.yaml#L95-L106) but this doesn't help distro packages. (Without this fix, [Bustle is unusable](https://bugs.freedesktop.org/show_bug.cgi?id=100220).)

**Comment by infrastation** [comment]
That presumably had happened with libpcap 1.9.1.

**Comment by mcr** [comment]
Denis Ovsienko <notifications@github.com> wrote:
    > That presumably had happened with libpcap 1.9.1.

I imagine that we have no test cases to catch that.

**Comment by guyharris** [comment]
> That presumably had happened with libpcap 1.9.1.

Presumably meaning "1.9.0".

**Comment by guyharris** [comment]
> I imagine that we have no test cases to catch that.

We don't - a D-Bus capture to test that would be useful.

**Comment by wjt** [comment]
https://wjt.me.uk/misc/empty.pcap (not quite empty, gathered with `dbus-monitor --system --pcap >empty.pcap` then hitting `Esc`. I can cook up a PR if that's better?

**Comment by guyharris** [comment]
That capture file isn't readable with:

    tcpdump version tcpdump version 4.9.2 -- Apple version 79.60.2
    libpcap version 1.8.1 -- Apple version 67.60.2

but is readable with

    tcpdump version 4.9.3-PRE-GIT_2018_07_27
    libpcap version 1.9.1-PRE-GIT

(No, Apple didn't break it, and, no, the current 1.9 branch doesn't have changes for this issue that aren't already in 1.9.0, and, no, it's not post-4.9.2 changes in the tcpdump 4.9 branch that fixed it, so, yes, this is fixed in 1.9.0.)
