### ISSUE TITLE
Use of strlcat prevents build on Linux

### ISSUE THREAD

**Issue by rknall** [the-tcpdump-group/libpcap#547]
The use of strlcat prevents the build of the master branch on Linux. Although there is a support library for bsd-related handling, which would provide the linkage (it fails on a missing external reference when included by Wireshark), this is not a necessity on Linux builds, nor do they check for it.

I've create a patch, which replaces strlcat use on Linux with a strncat macro in portability.h and properly checks for it's existence first, but I am not sure if this is the right way to go. If so, I am happy to provide the pull-request, otherwise tell me how it should be changed, and I'll submit the patch accordingly.

**Comment by guyharris** [comment]
> The use of strlcat prevents the build of the master branch on Linux.

...if you're building with remote capture support.  The only files using it are `pcap-new.c`, which is for remote capture support, and `pcap-bpf.c`, which is for systems that have BSD-style BPF as the underlying capture mechanism - Linux uses `PF_PACKET` sockets instead, so `pcap-linux.c` is compiled instead of `pcap-bpf.c`

> I've create a patch, which replaces strlcat use on Linux with a strncat macro in portability.h and properly checks for it's existence first, but I am not sure if this is the right way to go.

That's how we handle `strlcpy()`, so that's how we should handle `strlcat()`.

**Comment by guyharris** [comment]
This should be fixed by change e000478ecd3d7671d3fc65b50ad6fc8f39114d96.
