### ISSUE TITLE
pcap_compile() sometimes returns “illegal token”

### ISSUE THREAD

**Issue by jndxmlm** [the-tcpdump-group/libpcap#569]
hello everyone ，Thank you very much for your attention to my question, i have a bug that has been bothering me for two weeks，it is:

* libpcap version (e.g. from tcpdump --version)
libpcap 1.8.1

* operating system name and version and any other details that may be relevan (uname -a, compiler name and version, CPU type etc.)
centos 7（linux version 3.1.0-514.el7.x86_64）,gcc version 4.8.5,Thinkpad T430
my computer have two hardware network interfaces， my app achieve the function of monitoring the flow of the hardware network interfaces

* configure flags if any were used
configure with no flag

* statement of the problem
when i called "pcap_compile()" to compile filter, it returned -1 ,and pcap_geterr(handle) printf "illegal token"
This bug does not always occur when i run my app.

 steps to reproduce
1，downloaded the current git master branch of libpcap and the problem still occur;
2，commented the filter related code and my app occured kernel problem;
3，changed the paramter of the pcap_compile() from "pcap_compile(handle, &fp,filter_exp, 0,net)" to "pcap_compile(handle, &fp,filter_exp, 1,0)",always usless;
-------------my code is-----------------------

    void * net_recv_Thread(void* arg) 
    {  
        char dev[32]; /* name of the device to use */    
        char errbuf[PCAP_ERRBUF_SIZE];   

        struct bpf_program fp;		/* The compiled filter expression */
        char filter_exp[] = "tcp";
        unsigned int net;		/* The IP of our sniffing device */
        unsigned int mask;		/* The netmask of our sniffing device */
    
        strcpy(dev,NET_DEV_ETH);
        /* print out device name */   
        printf("ethDEV0: %s\n",dev);    

        if (pcap_lookupnet(dev, &net, &mask, errbuf) == -1) 
        {
            printf("Can't get netmask for device %s\n", dev);
            net = 0;
            mask = 0;
        }
        handle = pcap_open_live(dev,BUFSIZ,1,0,errbuf);
        if (handle == NULL)
        {
            printf("Couldn't open device %s: %s\n", dev, errbuf);
            exit(0);
        }
    
        if (pcap_datalink(handle) != DLT_EN10MB) 
        {
            printf("Device %s doesn't provide Ethernet headers - not supported\n", dev);
            exit(0);
        }
    
        if(pcap_compile(handle, &fp,filter_exp, 0,net) == -1)
        {
            printf("Couldn't parse filter %s: %s\n", filter_exp, pcap_geterr(handle));
            exit(0);
        }
    
        if (pcap_setfilter(handle, &fp) == -1)
        {
            printf("Couldn't install filter %s: %s\n", filter_exp, pcap_geterr(handle));
            exit(0);
        }
    
        pcap_loop(handle,-1,net_callback,NULL);
        return 0; 
    }

Thank you once again .

**Comment by guyharris** [comment]
Is `handle` a global variable?

If so, then is it accessed by any code running outside the thread whose initial function is `net_recv_Thread()`?

**Comment by jndxmlm** [comment]
@guyharris 
thanks，outside the net_recv_thread(), there is another thread air_recv_thread() ,the code is 
`void* air_recv_Thread(void* arg) 
{  
    char dev[32]; /* name of the device to use */    
    char errbuf[PCAP_ERRBUF_SIZE];   

    char filter_exp[] = "tcp";
    struct bpf_program fp;		/* The compiled filter expression */
    unsigned int mask;		/* The netmask of our sniffing device */
    unsigned int net;		/* The IP of our sniffing device */

    strcpy(dev,NET_DEV_ETH2);
    /* print out device name */   
    printf("ethDEV2: %s\n",dev);  

    if (pcap_lookupnet(dev, &net, &mask, errbuf) == -1) 
    {
        printf("Can't get netmask for device %s\n", dev);
        net = 0;
        mask = 0;
    }
    handle2 = pcap_open_live(dev,1514,1,0,errbuf);
    if (handle2 == NULL)
    {
        printf("Couldn't open device %s: %s\n", dev, errbuf);
        exit(0);
    }

    if (pcap_datalink(handle2) != DLT_EN10MB) 
    {
        printf("Device %s doesn't provide Ethernet headers - not supported\n", dev);
        exit(0);
    }

    if(pcap_compile(handle2, &fp, filter_exp, 0, net) == -1)
    {
        printf("Couldn't parse filter2 %s: %s\n", filter_exp, pcap_geterr(handle2));
        exit(0);
    }

    if (pcap_setfilter(handle2, &fp) == -1)
    {
        printf("Couldn't install filter %s: %s\n", filter_exp, pcap_geterr(handle2));
        exit(0);
    }

    pcap_loop(handle2,-1,net_callback2,NULL);
    return 0; 
}`

**Comment by guyharris** [comment]
So what happens if you make `handle` a local variable in `net_recv_Thread()` and make `handle2` a local variable in `air_recv_Thread()`?

**Comment by jndxmlm** [comment]
I change `handle,handle2` a local variable ,but the same error also occur .

**Comment by jndxmlm** [comment]
my problem solved but do not know why,
method is ：
move the open and setfilter code out of two thread
`   
if (pcap_lookupnet(dev, &net, &mask, errbuf) == -1) 
    {
        printf("Can't get netmask for device %s\n", dev);
        net = 0;
        mask = 0;
    }
    handle2 = pcap_open_live(dev,1514,1,0,errbuf);
    if (handle2 == NULL)
    {
        printf("Couldn't open device %s: %s\n", dev, errbuf);
        exit(0);
    }

    if (pcap_datalink(handle2) != DLT_EN10MB) 
    {
        printf("Device %s doesn't provide Ethernet headers - not supported\n", dev);
        exit(0);
    }

    if(pcap_compile(handle2, &fp, filter_exp, 0, net) == -1)
    {
        printf("Couldn't parse filter2 %s: %s\n", filter_exp, pcap_geterr(handle2));
        exit(0);
    }

    if (pcap_setfilter(handle2, &fp) == -1)
    {
        printf("Couldn't install filter %s: %s\n", filter_exp, pcap_geterr(handle2));
        exit(0);
    }
`

**Comment by guyharris** [comment]
If this is libpcap 1.8.1, that *should* allow multiple threads to run `pcap_compile()` at the same time (earlier versions did *not* allow that).

Have your program call `pcap_lib_version()` and print or otherwise display the string it returns.  If that's a value less than 1.8.0, such as 1.7.4, then the problem is that you're using a version of libpcap that doesn't allow multiple threads to call `pcap_compile()`.  If it's 1.8.0 or later, there's probably a bug somewhere in libpcap that's preventing multiple threads from being able to call `pcap_compile()`.

**Comment by jndxmlm** [comment]
my program called `pcap_lib_version()` and printed `lipcap version 1.5.3`
but my lipcap lib was downloaded version 1.8.1 from `http://www.tcpdump.org/`
thank you very much.

**Comment by guyharris** [comment]
> my program called `pcap_lib_version()` and printed `libpcap version 1.5.3`

That means that either 1) it was statically linked with libpcap 1.5.3 or 2) it was dynamically linked, possibly with a different version, but the run-time linker found libpcap 1.5.3 and linked it with that version.

What does `ldd` print when you run it on your program?  If, for example, the program is called `myanalyzer` and you run it as `./myanalyzer`, what does the command `ldd ./myanalyzer` print?

**Comment by jndxmlm** [comment]
I run `ldd ./app ` , it print `lipcap.so.1=>/lib64/lipcao.so.1`

**Comment by jndxmlm** [comment]
I run ldd ./app , it print lipcap.so.1=>/lib64/libpcap.so.1

**Comment by jndxmlm** [comment]
I open `/lib64/`, found libpcap.so.1.5.3 in it ,not 1.8.1

**Comment by guyharris** [comment]
> I run `ldd ./app` , it prints `libpcap.so.1=>/lib64/libpcap.so.1`

So it's dynamically linked with libpcap.

> I open `/lib64/`, found libpcap.so.1.5.3 in it ,not 1.8.1

So CentOS 7 ships with an older version of libpcap - and that version does *NOT* support running `pcap_compile()` at the same time in separate threads; the behavior if two threads are both executing in `pcap_compile()` are unpredictable, and can include parsing errors such as the one you're seeing.

Your program is running with the version of libpcap that ships with CentOS 7, *not* with the version of libpcap you built from source.

So you have two choices:

1. Make sure your app is linked, *and* will run, with the version of libpcap you built.  Either you will have to build it and force it to be linked *statically* with the `libpcap.a` that you built, or you will have to build *and* install the shared version of the library, and run `ldconfig` as root so the run-time linker knows about the new shared library, and then build the app, making sure it's linked with the new version (so that `ldd ./app` prints something such as `libpcap.so.1 => /usr/local/lib/libpcap.so.1`, or something such as that).

2. Add a pthread mutex to your program, lock it before all calls `pcap_compile()`, and release it once `pcap_compile()` returns, so that it will work even with a version of libpcap that doesn't support running `pcap_compile()` simultaneously in multiple threads.

**Comment by jndxmlm** [comment]
I got it ,thank you very much @guyharris
