### ISSUE TITLE
Issue with pcap_inject on Solaris 11

### ISSUE THREAD

**Issue by Betsy0129** [the-tcpdump-group/libpcap#571]
My tool is using libpcap 1.5.1-0.175.3.14.0.1.0 which is installed with the OS image on Solaris 11. I see an error when I call pcap_inject with a packet within 14 bytes of the MTU. The data to be transmitted is a full packet containing the ethernet headers but the return value indicates the packet is too large. I believe I found the reason for the issue (http://tcpdump-workers.tcpdump.narkive.com/S5CAU5dp/libpcap-raw-write-to-ethernet-header-not-working-under-solaris). It appears that DLIOCRAW ioctl needs to be set but I don't see a way to specify this. I don't believe there is a way for my tool to modify the file descriptor 
used in pcap_open_live.

**Comment by guyharris** [comment]
> It appears that DLIOCRAW ioctl needs to be set

That's true only if a STREAMS/DLPI descriptor is being used.  Solaris 11 supports BPF, and libpcap-from-tcpdump.org, at least, uses BPF in preference to DLPI.  I don't know what the libpcap that is shipped with Solaris does, but I think there were at least some changes submitted to libpcap from Oracle to make it use BPF on Solaris if it's available, so they might be using BPF.

What happens if you run your tool under `truss`?  Is it opening a BPF device and making BPF ioctls, or is it opening a DLPI device and making STREAMS DLPI ioctls?

**Comment by Betsy0129** [comment]
Looks like it is using bpf-->  open("/dev/bpf", O_RDWR)  
Any ideas about the inject failures when size is within 14 bytes of MTU?

**Comment by guyharris** [comment]
So what's the return value of `pcap_inject()`, and, if it's -1, what does `pcap_geterr()` return?

**Comment by guyharris** [comment]
A quick look at the Illumos source (the Solaris source being unavailable - thanks, Larry!) suggests that writing raw Ethernet packets, complete with the MAC header, might be impossible with BPF on Solaris (unlike BPF on BSD-flavored operating systems).

**Comment by Betsy0129** [comment]
I got bumped off machine temporarily for someone else to run some tests but I will double check return codes when I get back on Some packets with complete ethernet headers are successfully transmitted though, only seem to have issues with ones of size 1486-1500 (mtu 1500).

**Comment by Betsy0129** [comment]
Got back on machine and something is different. I am viewing the incoming traffic concurrently with snoop and although TCP MSS 1460 and datalink MTU 1500, incoming packet is 14 bytes higher. My tooling is capturing and retransmitting to incorrect inbound explains error I am seeing with outbound transmit errors.

**Comment by Betsy0129** [comment]
I seem to find multiple hit on similar issues and would like some clarification/instruction how to deal with this. 

OS reports MTU 1500. This is the size without the Ethernet link-layer header so packets on the wire could be larger (1514, maximum, in my case). pcap_inject allows raw packet (including link layer) to be transmitted so it could be larger than MTU but error received that packet is "too large to send". This I conforming traffic and should not require fragmentation.

Is this a problem specifically with the Solaris distribution or something common on libpcap and if common, is there a way this situation should be handled so that a received packet could be retransmitted without having to fragment or change the contents?

**Comment by guyharris** [comment]
> pcap_inject allows raw packet (including link layer) to be transmitted so it could be larger than MTU but error received that packet is "too large to send".

If, when you send a packet on an Ethernet via `pcap_inject()` on Solaris, 1) the packet is transmitted as is, with the first 14 bytes being sent as the Ethernet header, but 2) you get an error if you try to transmit a packet larger than 1500 bytes, that's a Solaris bug, because that behavior is completely pointless.

Either 1) they should treat the packet as the Ethernet *payload*, and add a MAC header or 2) they should treat the packet as a raw Ethernet packet, and allow up to 1514 bytes - i.e., impose a limit based on what the hardware can send, *not* based on the MTU, as the MTU doesn't include the link-layer header.  \*BSD and macOS/Darwin BPF do 2); another quick look at Illumos suggests that it - and probably Solaris - are doing two checks against the MTU, one of which (in `bpf_movein()`) correctly checks the packet length *minus* the MAC header length against the MTU, and the other of which, in `bpfwrite()`, *in*correctly checks the *entire packet length*, *including* the MAC header, against the MTU.

> Is this a problem specifically with the Solaris distribution

Yes.  Libpcap is a library that provides a common API atop various OSes different packet capture and injection mechanisms.  It relies on the OS not doing something stupid; apparently, Solaris does something stupid.  I'd suggest filing a bug with Oracle on this.
