### ISSUE TITLE
Pylibpcap/python-libpcap ZC support

### ISSUE THREAD

**Issue by rong00gle007** [the-tcpdump-group/libpcap#573]
Hi everyone, 

I have PF_Ring ZC installed and configured with libpcap, tcpdump and dumpcap.
But i am looking work with python and using pylibpcap/python-libpcap which is a wrapper of libpcap.

So i have doubt that if libpcap support  zc, should pylibpcap also support zc without making change in its code?
If anybody can give hint or direction that would be appreciated? thanx in advance

**Comment by mcr** [comment]
I don't know what PF_Ring ZC is, but google found: https://www.ntop.org/products/packet-capture/pf_ring/pf_ring-zc-zero-copy/
So my guess is that if your python-libpcap is using the correct libpcap library, then it should work.

**Comment by guyharris** [comment]
python-libpcap is probably just using the standard libpcap APIs; it's probably not using all the extra APIs that the PF_Ring version of libpcap adds.  If it's a requirement to use those new APIs, they'd have to somehow have python-libpcap use them if it's using PF_Ring libpcap rather than standard libpcap.

In addition, even if the new APIs *don't* have to be used, if PF_Ring ZC installs a separate version of libpcap, python-libpcap would somehow have to be told to load to use that version rather than the standard system version, just as you have to do with tcpdump and dumpcap.

None of this is a libpcap issue.
