### ISSUE TITLE
how to compile libpcap with mmap support

### ISSUE THREAD

**Issue by TidyHuang** [the-tcpdump-group/libpcap#575]
Anyone can give me a guide about how to compile libpcap with mmap support. I saw it only enabled by define Macro HAE_TPACKET3,

 I tried to use -DHAVE_TPACKET3 and HAVE_PACEKET3=1 when configuring, but I didn't found this passed value in config.h.

Thanks,
Tidy

**Comment by guyharris** [comment]
> I saw it only enabled by define Macro HAE_TPACKET3

No, it's enabled by 1) compiling for Linux, 2) compiling for a Linux that *has* mmap support, and 3) not running the configure script with `--disable-packet-ring`.

If you're not doing all three of those, you can't get Linux mmap support; if you're compiling for FreeBSD, you can get FreeBSD mmap support, otherwise there is no mmap support to get.

**Comment by TidyHuang** [comment]
Got it, thanks Guy Harris very much!
