### ISSUE TITLE
Conan package support

### ISSUE THREAD

**Issue by uilianries** [the-tcpdump-group/libpcap#593]
**What?**  
Provide [Conan](https://conan.io) recipe for libpcap project to distribute the project as package around the world.

**Why?**  
Conan could help to distribute libpcap binaries, solve project dependencies and automate project build (including Travis, AppVeyor and Gitlab).  
BTW, I created conan recipe for libpcap (as 3-party). Would be nice include a native recipe in the project. I could help to develop the recipe.

**Comment by gvanem** [comment]
Your link points to `https://github.com/the-tcpdump-group/libpcap/issues/conan.io` ->
`Not Found`. You mean this: `https://conan.io/`?

**Comment by uilianries** [comment]
@gvanem Fixed! Thanks!

**Comment by infrastation** [comment]
Thank you for the suggestion but as you can see libpcap source code tree does not contain any package management scripts/manifests/declarations. The people that use a particular package manager maintain the props independently of the source code because they change them whenever they want and however they want -- the upstream projects usually do not need to be involved when the maintainer adjusts e.g. filesystem layout or some other detail that is internal to the distribution. Moreover, different distributions could use the same package manager (e.g. RPM) but have different RPM spec files for libpcap.

Not being involved in those processes has proved to work well for everybody, this way if conan.io wants to package libpcap that is generally great but if that requires changes in libpcap someone would need to suggest specific changes, perhaps as a pull request, and explain why it needs to be done as proposed. Otherwise it is difficult to see how this matter could progress.

**Comment by uilianries** [comment]
@infrastation Thank you for your comments and time to explain. Now I can understand this project better. So, I'm going to keep a separate Conan recipe for libpcap, as I have done.

Regards!
