### ISSUE TITLE
Linux netfilter misbehaves with a max packet count

### ISSUE THREAD

**Issue by Nyangawa** [the-tcpdump-group/libpcap#601]
**libpcap version**: latest master branch

**problem**:

Using pcap_next_ex on netfilter devices like NFLOG/NFQUEUE may possibly cause packet loss.

**detail**:

When calling pcap_next_ex on live netfilter devices, it eventually calls `netfilter_read_linux` with second parameter `max_packets` values 1.

https://github.com/the-tcpdump-group/libpcap/blob/master/pcap.c#L319

But in the implementation of `netfilter_read_linux`, it reads every byte from the buffer and does not respect the `max_packets` parameter.

https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-netfilter-linux.c#L89

So, when there's more than 1 packet in the buffer, the function of pcap_next_ex will return `count` of packets, however only one of those packets are captured.

**Comment by guyharris** [comment]
That's a general problem with `pcap_dispatch()` with a max packet count; `pcap_next_ex()` is just a special case.

The loop in `netfilter_read_linux()` needs to be changed to resemble, for example, the loop in `pcap-bpf.c`, so that it 1) checks the max packet count and 2) if it exits the loop because it's reached the max packet count, saves the current buffer location and count and, the next time it's called, picks up from where it left off in the buffer rather than always reading into the buffer and starting at the beginning of the buffer.

**Comment by guyharris** [comment]
So this should be fixed now, as the pull request was merged.
