### ISSUE TITLE
How to set buffer size more than 2GB

### ISSUE THREAD

**Issue by wsotest** [the-tcpdump-group/libpcap#651]
I am using libpcap in tcpdump and pcapsipdump (https://sourceforge.net/projects/pcapsipdump/).
Now on version 1.8.1 and both programs have same limitation - it's not possible to set buffer size larger than 2048MB. 
As i find both Tcpdump and pcapsipdump has the option -B to set the capture buffer size. The value is then passed to libpcap via pcap_set_buffer_size() function. Tcpdump manpage does not specify in what units the buffer size is specified with -B, but from the source it seems that in KiB and default value is 2MB.
(https://github.com/mcr/libpcap/blob/9b67fb6b670d255f496fcdf280a7cf8692137ea2/pcap-linux.c#L3394).
So when I try to set huge buffer size - I get errors like that:

tcpdump -B 2100000
tcpdump: invalid packet buffer size

pcapsipdump -B 2147483648
Invalid option '-B 2147483648'.
  Argument should be positive integer with optional quantifier.
  e.g.: '-B 32768' or '-B 10KB' or '-b 512MiB', etc.

It looks suspicious that limitations is right  as INT_MAX 2147483647. Is it possible to increase limitations for buffer size?

PS. Test system is 
CentOS Linux release 7.3.1611 (Core) 4.13.5-1.el7.elrepo.x86_64

**Comment by wsotest** [comment]
> Are you sure you need a buffer that large?

Yes and short explanation why.
We use pcapsipdump for dumping all RTP traffic (audio and video) going through our media servers. And in practice we get that results:
```
Buffer_size   | Simultaneous_SIP_Calls
------------------------------------
2GB           |  around 5000 (pps 15k)
1.5GB         |  around 4000
1 GB          |  around 2000
```

So we have bottleneck here- pcapsipdump can't parse so high pps traffic and libpcap cant  save so high pps traffic in buffer cause don't have more memory.

**Comment by infrastation** [comment]
Well, if it cannot process the data fast enough, making the buffer bigger will result in a full buffer anyway, just the buffer will be bigger, right?

**Comment by guyharris** [comment]
Expanding on what Denis said:

On a network running full-speed at 1 Gb/sec, a 64 GB buffer can hold about 512 seconds worth of data.

If the application capturing the traffic simply cannot process packets at a 1 Gb/sec line rate, that means that it will be able to capture at most 512 seconds = 8 1/2 minutes of traffic; it *will* start dropping packets after that point.

If it can, on average, process packets at that rate, then a buffer that large would allow it to avoid dropping packets even if it *temporarily* drops below that rate, as long as it catches up before 8 1/2 minutes have expired.

So is the problem that pcapsipdump can't process packets at line rate, in which case you'll need a buffer large enough to handle the longest period of time during which you're going to be capturing, or is the problem that it can't guarantee that it won't *temporarily* drop below line rate, in which case you'll need a buffer large enough to handle the largest  period of time during which you can expect it to fall below line rate?

In either case, if you need more than a 2 GB buffer, you'll have to add a new API to libpcap and change the structure member used to store the buffer size (or store it in units of blocks of some size, e.g. pages, rather than in units of bytes).  You won't be able to get more than 2 GB with standard libpcap as it currently exists.
