### ISSUE TITLE
Using pcap_inject for rapid transmissions

### ISSUE THREAD

**Issue by shusain93** [the-tcpdump-group/libpcap#671]
I've written a custom wireless system/driver which works on top of a wifi card with packet injection and is in monitor mode. My program uses `pcap_inject` to send packets over the wireless device.

It works just fine with any amounts of incoming traffic and with 1-2 packets per second outgoing (ICMP ping). The issue, however, is that when I start trying to transmit much faster (TCP, more useful protocols at 25+ packets per second) I quickly seem to run out of buffer and my program errors out with `Failed to inject packet: send: Resource temporarily unavailable`. 

This doesn't make any sense to me. I know for a fact that my wireless card can transmit fast enough to handle TCP at rates of over 500Mb/s (so it's not saturating the TX ring buffer of the device) so I assume the issue lies somewhere else. I know that I'm processing TX packets fast enough given the resource unavailable error. [I think I'm in a similar solution as this poor guy five years ago
](https://ubuntuforums.org/showthread.php?t=1940332). I asked about this on the linux stackexchange and was pretty much told I needed to write my own kernel module since libpcap isn't meant to do this and so I just wanted to find out if a) this is true and b) if there's anything I could modify in my system to help libpcap since I don't need ultrahigh speed transfer, it just needs to be able to handle simple HTTPS negotiations in under 30 seconds

**Comment by guyharris** [comment]
> I asked about this on the linux stackexchange and was pretty much told I needed to write my own kernel module since libpcap isn't meant to do this and so I just wanted to find out if a) this is true

If somebody said something close to "you need to write your own kernel module since libpcap isn't meant to do this", they're confused, because libpcap isn't a kernel module, it's a library that, on Linux, sends packets by calling `send()` on a `PF_PACKET` socket.

What they should perhaps have said is "packet-at-a-time sends, using the `send()` system call on a `PF_PACKET` socket, wasn't intended to do this" - other code using the same mechanism, without using libpcap, will probably have the same problem.  (See the source to `pcap_inject_linux()` in libpcap's `pcap-linux.c` - there's not much to it.)

You're writing to a datagram socket, and the default send buffer size for the socket might not be large.  You could try increasing the buffer size, by setting the `SO_SNDBUF` option with a `setsockopt()` call on the descriptor for the socket (use `pcap_fileno()` to get the descriptor - but don't expect a `setsockopt()` call on that descriptor to work on other operating systems or on devices other than network interfaces on Linux).

If a bigger socket buffer doesn't help, *some* other kernel mechanism *might* be necessary.  Linux has "memory-mapped" support for `PF_PACKET` sockets; libpcap uses that for capturing traffic, but not for injecting traffic.  Look up `PACKET_TX_RING` for more information on that.

However, somebody found that it appeared to be slower than "having a buffer in memory and calling `sendto` repeatedly for every frame in the buffer that needs sending", and [asked about it on Stack Overflow](https://stackoverflow.com/questions/43193889/sending-data-with-packet-mmap-and-packet-tx-ring-is-slower-than-normal-withou); you might want to read that post (long though the question answer might be).

**Comment by shusain93** [comment]
Cranking the buffer solved the injection errors but I'm still not transmitting fast enough and so my gigantic 25MB buffer eventually fills up and starts spitting out `Failed to inject packet: send: No buffer space available`.

I know my rate is higher than the TX rate since when I eventually get a ping back I get lovely values like `109967.309 ms` (109s PING!) This also leads to some weird (but unsurprising) effects like packets still being transmitted by the system from the buffer after I've killed my program.

This after effect also gives some odd timings on back to back TX. Fastest I've seen between two packets is 20ms and the worst (commonly) I've seen is 1900ms. All coming out of the buffer of course so it should be going as fast as it can. 

Could this be a side effect of monitor mode on a really noisy channel? Since there's a ton of chat could the problem be that the card is waiting to TX when it finds silence. I wouldn't expect the card in monitor mode would respect the "only one person talking at once" rule of wifi but it looks like that since packets are coming out in bursts and then going silent for a bit and then another chunk. 

---

I did some testing with this theory, switched to an unused (with maybe a packet every few seconds) channel and then ran a ping with an interval of 0.0001 and transmitted over a thousand packets in a second. When I killed my program the ping requests immediately stopped. On the channel I was originally using I maxed out at 509 PPS and they kept transmitting well past when I killed the program. Even with the default buffer I didn't have any trouble hitting what I needed. 

This also explains why I got more errors when I was in the middle of a TCP connection with tons of duplicates and retransmits because it meant that my station wouldn't transmit, continually degrading itself until the connections reset and the air cleared and they could try again. A single error in the communication explodes and breaks the whole connection due to some weird amplification. 

I'm closing this since it's not a libpcap problem.

**Comment by bakwc** [comment]
Had simmilar issue. Setting large `SO_SNDBUF` with `setsockopt` helped. Also I had to increase OS buffer with `sudo sysctl -w net.core.wmem_max=26214400` (and `net.core.wmem_default`) - by default OS prevented setting large enough `SO_SNDBUF`.

**Comment by ezhes** [comment]
If you want closure, I ended up learning a while later that some hardware only injects packets at 1Mb/s (or whatever the slowest broadcast rate is) to ensure that they're visible to all clients. This isn't something you can really do anything to avoid and it sort of makes sense, but it's rather unfortunate.
