### ISSUE TITLE
pcap_inject after pcap_open_live

### ISSUE THREAD

**Issue by edge7** [the-tcpdump-group/libpcap#698]
Hi,
this is not a bug report. 

I am playing with libpcap and wondering how to forward packet after capturing it.
My question is:
As I am modifying a small part of the TCP payload, do I need to update the Ethernet/IP and TCP checksum to avoid it to be dropped or it is done automatically?
Also, even if I am using Wifi I see an Ethernet header, probably because it is a Linux abstraction. When modifying the checksum can I use just update the Ethernet header CRC field, and that's it?
Thanks,

**Comment by guyharris** [comment]
> As I am modifying a small part of the TCP payload, do I need to update the Ethernet/IP and TCP checksum to avoid it to be dropped or it is done automatically?

`pcap_inject()` will be transmitting a raw link-layer packet; the Internet protocol stack will not be involved, so the TCP checksum will *not* be updated - you will have to do so yourself.  The IP checksum only covers the IP header, so, unless you're modifying the header - changing IP addresses, changing the length of the payload, etc. - you won't need to modify that.  (If it's IPv6, there's no checksum *to* modify.)

The network adapter wil, however, probably recompute the link-layer checksum - in fact, you probably aren't even *capturing* the link-layer checksum, so there's no checksum in your packet *to* update.

> Also, even if I am using Wifi I see an Ethernet header, probably because it is a Linux abstraction

Probably because  you're not capturing in monitor mode.  If you're trying to forward modified data packets, there's no need to capture in monitor mode, and you probably don't *want* to capture in monitor mode.

> When modifying the checksum can I use just update the Ethernet header CRC field, and that's it?

As I indicated above, you won't be seeing the link-layer checksum, and won't have one to modify, so you don't update it.  (You *will*, however, as indicated, need to update the IP an

**Comment by edge7** [comment]
Hi,
thank you for your answer.
Now I am just experimenting without touching the packets:
I am on my Lan, with my Linux box running and my phone connected.
I ARP-spoofed the router and my phone, so am in the middle and I just want to redirect packages as Etthercap does.
So I have:
`pcap_loop(handle , -1 , process_packet , NULL);
process_packet(u_char *args, const struct pcap_pkthdr *header, const u_char *buffer){`
and in process_packet am checking if the DST IP address is the one of the phone change the ethernet MAC-ADDRESS to the one of the phone:
`struct ethhdr *eth = (struct ethhdr *)buffer;
   eth->h_dest[0] = 0xXX; ; eth->h_dest[1] = 0x07; eth->h_dest[2] =0x15; eth->h_dest[3]; 0x3D;  eth->h_dest[4] = 0xXX;  eth->h_dest[5] = 0x36; `
otherwise if the packet is for the Router (external IP Address) then set the mac address with the one of the router.
After this I just call:
`pcap_inject(handle, buffer, size);`

But there is no connectivity at all, my Phone is not able to surf Internet.
Am I missing something?
thanks

**Comment by edge7** [comment]
Quick update:
There was a small issue in the code. Now it works, I can confirm that, one can read, modify and forward packets using libcap.

Keep up the great work.
