### ISSUE TITLE
pcap_datalink() on SocketCan interface returned wrong DLT value

### ISSUE THREAD

**Issue by nypdmax** [the-tcpdump-group/libpcap#699]
Hello all,

I have a program woking well on my PC (ubuntu 16.04 amd64, with libpcap0.8 and libpcap0.8-dev installed from ubuntu apt repo, version 1.7.4) . Now I'm running that CAN bus monitor in my raspberry pi 3 and I found some issues.

While I'm opening a socketcan interface with libpcap

```
     char err_buff[PCAP_ERRBUF_SIZE];
     pcap_t *hl;

     hl = pcap_open_live(CAN_DEV.c_str(), BUFSIZ, 1, 1000, err_buff);
     if (hl == NULL)
     {
         /* open failed */
         std::cout << "Couldn't open device " << CAN_DEV << std::endl;
         std::cout <<" Error: " << err_buff << std::endl;
         return -1;
     }
 
     if (pcap_datalink(hl) != DLT_CAN_SOCKETCAN)
     {
         // it is not a socketCAN frame 
         std::cout << "Device doesn't use socketCAN, it use " << pcap_datalink(hl) << std::endl;
         return -1;
     } 
```

In both master and libpcap-1.8 branches, pcap_datalink(hl)  returned 113 (DLT_LINUX_SLL) instead of 227 (DLT_CAN_SOCKETCAN).

However on my PC it's working as expected.

FYI, my my raspberry pi 3 is running Linux 4.14.33. I've recompiled the kernel to support CAN devices and my PCAN-USB FD adapter. 
And I set up the CAN interface using:

`sudo ip link set can0 type can bitrate 500000 triple-sampling on`
`sudo ifconfig can0 up`
 
I used a simple socketcan program to test sending and receiving frames and found no problem.

Please advice... Any help is appreciated!

**Comment by guyharris** [comment]
> In both master and libpcap-1.8 branches, pcap_datalink(hl) returned 113 (DLT_LINUX_SLL) instead of 227 (DLT_CAN_SOCKETCAN).

It's supposed to do so.  See the long discussion in [Wireshark bug 12687](https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=12687).

So, if you want your program to work with pre-1.8 libpcap and libpcap 1.8 and newer, you will have to handle both `DLT_CAN_SOCKETCAN` *and* `DLT_LINUX_SLL`.

`DLT_LINUX_SLL` packets begin with a header containing, in order:

-  a 2-byte "packet type" which is one of:
0 - packet was sent to us;
1 - packet was broadcast;
2 - packet was multicast;
3 - packet was sent to somebody else;
4 - packet was sent *by* us;

- a 2-byte protocol field, which may contain an Ethernet protocol value or some special protocol value, including 0x000C for CAN packets and 0x000D for CAN FD packets;

- a 2-byte link-layer type, giving the type of link-layer address (a Linux `ARPHRD_` value);

- a 2-byte link-layer address length;

- an 8-byte source link-layer address, whose actual length is specified by the previous value, so that if the link-layer address length is *N*, only the first *N* bytes of the link-layer address field are valid, and the remaining 8-*N* bytes are padding (if *N* is greater than 8, the packet is malformed).

All fields other than the source link-layer address are big-endian.

For CAN packets, what follows is a CAN header, similar to what you get for `DLT_CAN_SOCKETCAN`, except that the multi-byte numeric fields are in *host* byte order rather than *network* byte order.

For CAN FD packets, see information in the Wireshark bug and in pages to which it links.

**Comment by nypdmax** [comment]
@guyharris Thank you for your reply!

My program was coded to send/receive standard CAN frames (not 'CANFD' frames). Also `ifconfig can0` showed the mtu is 16.

> For CAN packets, what follows is a CAN header, similar to what you get for DLT_CAN_SOCKETCAN, except that the multi-byte numeric fields are in host byte order rather than network byte order.

My understanding of your suggestion is a CAN frame always follows a `DLT_LINUX_SLL` packet (after all those fields you explained). In order to handle `DLT_LINUX_SLL` packets, I have to manually parse the following fields and convert them to something like `struct can_frame`. Is that correct? 

Also I'm still curious about why the pcap_datalink() returned different value. I mean, if it's something unsettled, then (on both my pc and my raspbeery pi) shall it return the same value (either DLT_LINUX_SLL or DLT_CAN_SOCKETCAN in both cases)?

**Comment by nypdmax** [comment]
@guyharris  Thank you for the detailed explaination!
