### ISSUE TITLE
[pcap-npf.c] Disconnected devices successfully opened

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/libpcap#700]
This is similar to this 4 year old [issue](https://github.com/the-tcpdump-group/libpcap/issues/336):

`NPF`  devices for disconnected adapters are reported as working in e.g.  `findalldevices.exe`:
```
\Device\NPF_{3A46ACA0-CBED-44BC-A239-6AEA3D0C451D}
        Description: Realtek PCIe GBE Family Controller
        Flags:
        Address Family: AF_INET
                Address: 10.0.0.10
                Netmask: 255.255.255.0
                Broadcast Address: 0.0.0.0

\Device\NPF_{F92984E3-5D40-4AD9-B054-41288EAE699F}
        Description: Microsoft
        Flags:
        Address Family: AF_INET
                Address: 10.0.0.11
                Netmask: 255.255.255.0
                Broadcast Address: 0.0.0.0
```

(empty `Flags:`) Only the first Ethernet adapter is up. The 2nd is a WiFi adapter.
Seems there is nothing in the code that sets `PCAP_IF_UP` and/or `PCAP_IF_RUNNING` for Windows.

For reference, `nmap --iflist` does a more decent job for this:
```
************************INTERFACES************************
DEV  (SHORT) IP/MASK              TYPE        UP   MTU  MAC
eth0 (eth0)  10.0.0.10/24         ethernet    up   1500 E0:3F:49:81:2E:EA
eth1 (eth1)  10.0.0.11/24         ethernet    down 1500 B0:7F:B9:4D:CE:DC
```

Not sure this is *Working as designed*, but the situation now is that capturing with TShark, Windump or whatever just sits there capturing nothing. Giving the impression the adapter is up but nothing is on the wire. At least those programs should warn that the adapter is down. 

But I get Windump to start capturing when bringing my WiFi adapter up after starting Windump. I also have a BlueTooth adapter, but haven't tried that (how do I get that up?)

Detecting a link-state would be *simple* to do with something like:
```c
/*
 * Ref: https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-media-connect-status
 */
static BOOL get_link_state (ADAPTER *adapter, int *state)
{
    struct {
        PACKET_OID_DATA oidData;
        DWORD state;
    } oid;
    memset (&oid, 0, sizeof(oid));
    oid.oidData.Oid = OID_GEN_MEDIA_CONNECT_STATUS;
    oid.oidData.Length = sizeof(oid);
    if (!PacketRequest(adapter, FALSE, &oid.oidData))
       return (FALSE);
    *state = *(int*) &oid.oidData.Data;
    return (TRUE);
}

/* And add to pcap_add_if_win32():
 */
int  link_state = -1;
if (get_link_state(adapter,&link_state) && link_state == 0)
   pcap_flags |= PCAP_IF_RUNNING | PCAP_IF_UP;
```

**Comment by guyharris** [comment]
On UN\*X, neither `IFF_UP` nor `IFF_RUNNING` guarantee that you're connected to a network; I just plugged my Thunderbolt Ethernet adapter into my Mac, and it's reported as both UP and RUNNING, even though there's no 8P8C connector plugged into the Ethernet side.

What does "disconnected" mean in this context?  "Plugged into an Ethernet network?"

Perhaps we need another PCAP_IF_CONNECTED flag that indicates whether there's anything to listen to on the interface.

**Comment by guyharris** [comment]
On UN\*Xes, neither UP nor RUNNING guarantee that you're connected to a network - I plugged my Thunderbolt Ethernet adapter into my MacBook Pro, and it was reported as UP and RUNNING even though it wasn't plugged into an Ethernet.

So maybe we need a `PCAP_IF_CONNECTED` flag.

The \*BSDs and macOS have a `SIOCGIFMEDIA` call that can report an "active" flag; there's no guarantee that an arbitrary adapter supports it (the loopback interface might not, as there's no medium involved), and it can indicate that the "active" flag isn't supported, so we might have to report "connected" for all up-and-running interfaces if we can't get the "connected" information.

On Linux, the ethtool ETHTOOL_GLINK operation might work, at least for Ethernet devices that are up.

**Comment by guyharris** [comment]
BTW, "connected" doesn't apply to Wi-Fi, and probably other wireless/fibreless networks, the way it does to wired networks.  It tends to be interpreted by the networking stack as meaning "associated with a network" for Wi-Fi, but you can capture, in monitor mode, even if you're not associated with a network (and, on some platforms, such as Windows, capturing in monitor mode explicitly disassociates you from the network).

Perhaps a `PCAP_IF_DISCONNECTED` flag is what we should have, and limit it to networks where you *have* to be plugged in to see any traffic.

**Comment by gvanem** [comment]
And I just tried with NPcap (since you mentioned monitor-mode).  With this, `findalldevstest.exe` in addition reports:
```
Preferred device name: \Device\NPF_{AB5342E8-E148-46B1-A7DC-D09868C7D3D4} 
```
An adapter that is also *dis-connected*. So the confusion is pretty complete.

**Comment by guyharris** [comment]
> I agree that the problem is not a clearly working / non working in case of WiFi.

So maybe there needs to be a `PCAP_IF_WIRELESS` flag (documented with a very emphatic "wireless means *WIRELESS*, not just *WI-FI*, so it could, for example, be Bluetooth - *DO NOT* assume these are necessarily Wi-FI interfaces" note), so that "connected" and "disconnected" can be interpreted differently.

That gives you "wired" interfaces (even if the "wire" is made out of glass), "wireless" interfaces (radio,  infrared, anything else that goes "over the air" rather than over a medium that has to be plugged in), and "loopback".  (We might add a fourth category for "goes over something that's not pluggable or over-the-air but isn't loopback" such as virtual-machine-to-virtual-machine connections, if distinguishing between that and "wired" matters.)

There should probably also be a *two*-bit field for the connection status, with values of "connected", "disconnected", "unknown", and "not applicable".  "Unknown" would be used if we don't have an API to get the status or the API doesn't provide the status; "not applicable" would be used, for example, for loopback adapters.  That way, you don't report the status of interfaces where the connection status is unknown as "disconnected" or "connected", and you don't report the status of interfaces where the connection status doesn't apply at all.

> I'm not sure how/where to check for this link-state; libpcap or tcpdump..

libpcap, so that tcpdump and Wireshark and... can all 1) let the user know and 2) prefer connected, at least for wired interfaces.  libpcap would also use that *internally* to sort the list of interfaces, which would mean that the process of picking the default interface would prefer connected wired interfaces to disconnected wired interfaces.

**Comment by gvanem** [comment]
@sgeto 
> In which header is  OID_GEN_MEDIA_CONNECT_STATUS set? I hope not in a WDK-only file.

No, in the SDK-header `ntddndis.h`.

> What's Lwip?

Lightweight tcp/ip stack; https://savannah.nongnu.org/git/?group=lwip

**Comment by guyharris** [comment]
So does the current master branch of libpcap work?  It has the new `PCAP_IF_WIRELESS` flag, and the connected/disconnected indications, and penalizes disconnected interfaces in the interface list, so they should come after connected ones.

It still *lists* them, and lets you open them.  tcpdump and \*shark don't currently report that information; I'll add that to tcpdump next (it should be in 4.10, although it'd obviously also require libpcap 1.9), and to Wireshark for 3.0.

**Comment by gvanem** [comment]
Thank Guy, that is much better. From `findalldevstest.exe` now:
```
\Device\NPF_{3A46ACA0-CBED-44BC-A239-6AEA3D0C451D}
        Description: Realtek PCIe GBE Family Controller
        Flags:  (connected)
        Address Family: AF_INET
                Address: 10.0.0.10
                Netmask: 255.255.255.0
                Broadcast Address: 0.0.0.0

\Device\NPF_{F92984E3-5D40-4AD9-B054-41288EAE699F}
        Description: Microsoft
        Flags: WIRELESS (not associated)
        Address Family: AF_INET
                Address: 10.0.0.11
                Netmask: 255.255.255.0
                Broadcast Address: 0.0.0.0

\\.\airpcap00
        Description: AirPcap USB wireless capture adapter nr. 00
        Flags:  (connection status unknown)

\Device\NPF_{AB5342E8-E148-46B1-A7DC-D09868C7D3D4}
        Description: Microsoft
        Flags: WIRELESS (not associated)
        Address Family: AF_INET
                Address: 10.0.0.19
                Netmask: 255.255.255.0
                Broadcast Address: 0.0.0.0

Preferred device name: \\.\airpcap00
Preferred device is on network: 0.0.0.0/0.0.0.0
```
But still several problems:
*  My `\\.\airpcap00` is *not* identified as a `WIRELESS`.
*  My `\\.\airpcap00` is the *preferred* device. I assume that's because `pcap_lookupdev()` on Win32 doesn't take into account `get_figure_of_merit()`?

Making this patch to `pcap-npf.c / get_flags()` fixes the first issue:
```diff
@@ -1481,6 +1481,24 @@
                return (0);
        }

+#ifdef HAVE_AIRPCAP_API
+       /*
+        * Airpcap.sys do not support the below 'OID_GEN_x' values.
+        * Just set these flags (and none of the '*flags' entered with).
+        */
+       if (PacketGetAirPcapHandle(adapter)) {
+               /*
+                * Must be "up" and "running" if the above if succeeded.
+                */
+               *flags = PCAP_IF_UP | PCAP_IF_RUNNING;
+
+               /*
+                * An airpcap device is a wireless device (duh!)
+                */
+               *flags |= PCAP_IF_WIRELESS;
+
+               /*
+                * A "network assosiation state" makes no sense for airpcap.
+                */
+               *flags |= PCAP_IF_CONNECTION_STATUS_NOT_APPLICABLE;
+               PacketCloseAdapter(adapter);
+               return (0);
+       }
+#endif
+
```

I wounder if ` PCAP_IF_UP | PCAP_IF_RUNNING` should also be set for non-Airpcap if one of the `IO_GEN_x` calls succeeds?

**Comment by guyharris** [comment]
> My `\\.\airpcap00` is *no*t identified as a `WIRELESS`.

I've checked in your change.

> My `\\.\airpcap00` is the *preferred* device.

Is that with, or without, your change?

> I assume that's because `pcap_lookupdev()` on Win32 doesn't take into account `get_figure_of_merit()`?

There are two ways to get the preferred device with "recent" versions of {llibpcap,WinPcap} (I put "recent" in quotes because `pcap_findalldevs()` is at *least* ten years old) - call `pcap_lookupdev()`, and call `pcap_findalldevs()` and use the first device in the list.

In "recent" versions of libpcap on UN\*X, `pcap_lookupdev()` is just a routine that does the second of those two, so the two are equivalent, so, on UN\*X, `pcap_lookupdev()` takes into account the figure of merit, because `pcap_findalldevs()` does.

On Windows, `pcap_lookupdev()` is a separate routine, for reasons explained in the comment before the `pcap_lookupdev()` in `pcap-npf.c`:

     * In the best of all possible worlds, this would be the same as on
     * UN*X, but there may be software that expects this to return a
     * full list of devices after the first device.

I.e., it was WinPcap's `pcap_findalldevs()`-equivalent before there *was* `pcap_findalldevs()`.  Wireshark (under the name of "Ethereal" at the time) used it on Windows, and used `SIOCGIFCONF` ioctls on UN\*X, before there was `pcap_findalldevs()`.  It now uses `pcap_findalldevs()` if present, but there might still be software that uses `pcap_lookupdev()` in WinPcap to get a list of devices.

So, on Windows, `pcap_lookupdev()` will, if you treat it as a routine that just returns one device rather than as a set of devices (i.e., treat it as if it did only what the UN\*X version does), give you the first device that the NPF driver gives you.  I wouldn't *expect* it to give you the AirPcap device first, but it might.

`pcap_lookupdev()` is deprecated - not only does it now behave differently on UN\*X and Windows even if you're just asking for a single device (it takes the figure of merit into account on UN\*X but not on Windows), but it has always returned a pointer to a static buffer (going back at least to libpcap 0.4) and is thus not necessarily thread-safe.  And that's "deprecated" as in "if the compiler supports it, you'll get a deprecation warning if you use it".

Both tcpdump and Wireshark use the "call `pcap_findalldevs()` and use the first device" mechanism to pick the default device and have done so for quite a while.  If a program uses `pcap_findalldevs()` on Windows when using libpcap with your change (with either WinPcap's or NPcap's `packet.dll` and river), the AirPcap devices will appear first because they're "up" and "running" but the regular network interfaces aren't, and thus have a better "figure of merit" than the regular network interfaces.

> I wonder if `PCAP_IF_UP | PCAP_IF_RUNNING` should also be set for non-Airpcap if one of the `IO_GEN_x` calls succeeds?

(Presumably meaning "`OID_GEN_x` calls")  Or perhaps set always - I'm not sure whether Windows has the equivalent of "up" and "running".  I'm not sure whether the meanings of those flags are documented for any UN\*X; macOS (and probably other BSD-flavored OSes) doesn't document them except in the `net/if.h` header file, where the comment for `IFF_UP` says "interface is up" and the comment for `IFF_RUNNING` says "resources allocated", neither of which are very specific or enlightening.

In some notes I had when looking at those flags for Windows, I noted that, for NDIS 5, `OID_GEN_HARDWARE_STATUS` returns either `NdisHardwareStatusReady`, meaning "Available and capable of sending and receiving data over the wire", or something else, and asked whether that corresponds to `IFF_RUNNING` or to both `IFF_UP` and `IFF_RUNNING`.  It may be that you can't distinguish the two in Windows; Winsock has a call that gives `IFF_UP` but not `IFF_RUNNING`.

On UN\*X, "up" and "running" doesn't imply "connected", so "up", "running", and "connected" should be treated separately.

So I'm not entirely sure what to do about "up" and "running".  If Windows simply has no notion of devices that aren't "up" and "running", we should probably label all interfaces as "up" and "running", and leave it up to the "connected" state to indicate which devices are "better".  Or perhaps we should use the Winsock call in question and label all "up" devices as both "up" and "running".

**Comment by gvanem** [comment]
> Is that with, or without, your change?

Both. My change did not change that since `pcap_lookupdev()` is the one in `pcap-npf.c` (as you aptly describes)

> Winsock has a call that gives IFF_UP but not IFF_RUNNING.

Presumably you mean [GetInterfaceInfo()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365947(v=vs.85).aspx). That works for interfaces with an IPv4 address. Not for an IPv6-only interface AFAICS. 

*BTW*. Some descriptions from NPF. Like ` Description: Microsoft` above is too vague compared to what *IpHlpAPI* gives;  `Description:  802.11ac Wireless LAN Card` is way more descriptive. I'm not sure if WinPcap truncates the description?

**Comment by guyharris** [comment]
> Some descriptions from NPF

Pre-Vista(?) Windows only offered a "vendor string" description, such as "Realtek PCIe GBE Family Controller", as far as I know.  I think something about the way NDIS 6 works turns that into "Microsoft" for some interfaces (Wi-Fi interfaces?).

Is the IpHlpAPI description the "friendly name", e.g. "Local network connection" or whatever your first interface defaults to being called?  A comment in the Wireshark code to get the "friendly name" says "The functions required to do this all reside within iphlpapi.dll".

Ultimately, I'd like to:

- have pcapng support both "friendly names" and "device descriptions" in Interface Description Blocks;

- have a replacement for `pcap_findalldevs()` that returns IDB options (so that it's extensible)

and have the new API provide the "friendly name" on Windows (and macOS and the BSDs that have a "get a description" ioctl), as well as providing the device description on, at minimum, Windows, and try to work around the "Microsoft" problem.  `pcap_findalldevs()` might provide the friendly name as the description if it exists and the device description if the friendly name doesn't exist but the device description does.

**Comment by guyharris** [comment]
> Presumably you mean [GetInterfaceInfo()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365947(v=vs.85).aspx).

No, the `SIO_GET_INTERFACE_LIST` [`WSAIoctl()`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms741621(v=vs.85).aspx) call; the [`INTERFACE_INFO`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms738568(v=vs.85).aspx) structure has an `iiFlags` field with an `IFF_UP` flag, with a description every bit as helpful as the `net/if.h` comments on UN\*X - "The interface is running.".

**Comment by guyharris** [comment]
OK, [`OID_GEN_HARDWARE_STATUS`](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-hardware-status) may get the information we need; I've changed `pcap-npf.c` to use that OID and set "up" and "running" based on the result:

- `NdisHardwareStatusReady`: up and running

- `NdisHardwareStatusInitializing`, `NdisHardwareStatusReset`: up but not running

- `NdisHardwareStatusClosing`, `NdisHardwareStatusNotReady`: neither up nor running

I was unable to get interfaces on my (virtual) machines in any state other than `NdisHardwareStatusReady` (including the non-virtual USB Wi-Fi adapters I plugged in).

**Comment by guyharris** [comment]
Speaking of OIDs, [`OID_GEN_FRIENDLY_NAME`](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-friendly-name) might fetch the "friendly name".

**Comment by guyharris** [comment]
Also, for NDIS 6, [`OID_GEN_OPERATIONAL_STATUS`](https://docs.microsoft.com/en-us/windows-hardware/drivers/network/oid-gen-operational-status) might also get some sort of "up"/"down" status; if that's used, "running" should probably be a copy of "up", as I'm not sure whether Windows has a notion of "interface is up but resources aren't allocated", especially given that no UN\*X I know of explains what the "resources" in question are....

**Comment by gvanem** [comment]
I tried experimenting with `IOD_GEN_OPERATIONAL_STATUS`, but failed. Presumably since WinPcap uses NDIS 5 and `OID_GEN_OPERATIONAL_STATUS` is a NDIS 6.0+ function.

Besides, IpHlpAPI and [GetAdaptersAddresses()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx) returns an `IfType == 6` (Ethernet) for my BlueTooth adapter.

**Comment by guyharris** [comment]
> Besides, IpHlpAPI and [GetAdaptersAddresses()](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365915(v=vs.85).aspx) returns an `IfType == 6` (Ethernet) for my BlueTooth adapter.

Perhaps because the adapter isn't "raw Bluetooth" but "Bluetooth for IP networks", so there's an adaptation layer in the software providing fake Ethernet packets to the IP stack and accepting Ethernet packets from the IP stack.

**Comment by gvanem** [comment]
> .. providing fake Ethernet packets to the IP stack ..

Something like that, yes.

**Comment by mcr** [comment]
It looks like this issue is closed. Please re-open if you disagree.
