### ISSUE TITLE
Libpcap - pcapng full read/write support

### ISSUE THREAD

**Issue by fruffy** [the-tcpdump-group/libpcap#728]
As far as I know, several small [libraries](https://github.com/pcapng/pcapng/wiki/Implementations) already exist which support the reading and writing of pcapng files. However, libcap itself seems to implement only extremely limited functionality. Is there a plan to fully support pcapng soon? If so, is there an ETA for a release?

**Comment by guyharris** [comment]
> Is there a plan to fully support pcapng soon?

No.

**Comment by mcr** [comment]
Guy Harris <notifications@github.com> wrote:
    > Is there a plan to fully support pcapng soon?

    > No.

no, there is no *plan*.
If you want to be involved in making a plan, that's more than welcome!

**Comment by guyharris** [comment]
> If you want to be involved in making a plan, that's more than welcome!

Perhaps including both API design (the current capture-file-reading API isn't sufficient) and implementation.

Note that it would probably be best if the new API could also be used to read pcap files (pretend it has a single IDB, with no name), so that tcpdump, for example, can read pcap or pcapng files without having to know which kind of file it's opening (I'm looking at *you*, Apple!).  (Also, use `pcapng` rather than `pcap_ng` in the names, so we don't collide with Apple's undocumented versions, which, in addition to having the aforementioned problem, are licensed under the APSL, which has patent clauses that might be an issue for GPL fans.)

Doing this right isn't a quick project, hence no plan to support soon.

**Comment by eric-olsson-hiq** [comment]
Hi, I'm interested if plans have changed regarding pcapng - I haven't seen much discussion in the past couple years about pcapng support.

**Comment by mcr** [comment]
Gotta get tcpdump 5.0 released first.
If you have ideas on API, then it would be great to write up documentation as
a proposal.

**Comment by guyharris** [comment]
Duplicate of #1321
