### ISSUE TITLE
pcap_lookupnet IP returning is not what ifconfig returns

### ISSUE THREAD

**Issue by malay75** [the-tcpdump-group/libpcap#740]
in pcap_lookupnet 

this line :
*netp &= *maskp;

before returning is it intentional needed ?

regards

**Comment by guyharris** [comment]
To quote the `pcap_lookupnet()` man page:

    $ man pcap_lookupnet
    PCAP_LOOKUPNET(3PCAP)                                    PCAP_LOOKUPNET(3PCAP)
    
    NAME
           pcap_lookupnet - find the IPv4 network number and netmask for a device

The network number is the IPv4 address ANDed with the netmask, so as to clear the bits that are part of the local address rather than part of the network number.

`ifconfig` reports something such as:

    $ ifconfig en0
    en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether XX:XX:XX:XX:XX:XX 
        inet6 XXXX:XXXX:XXXX:XXXX:XXXX%en0 prefixlen 64 secured scopeid 0x4 
        inet 192.168.42.66 netmask 0xffffff00 broadcast 192.168.42.255

so it *doesn't* report the IPv4 network number and netmask, it reports the IPv4 *network address* and netmask.

So, yes, the ANDing is intentional and, yes, it is also intentional that `pcap_lookupnet()` doesn't return the IPv4 network address that `ifconfig` shows.
