### ISSUE TITLE
Allow pcap_dump_fopen to work on Windows even when differing CRTs are used

### ISSUE THREAD

**Issue by MadAlexUK** [the-tcpdump-group/libpcap#805]
`pcap_dump_fopen()` is not safe on Windows because the caller may be using a C runtime that differs from that used by libpcap. There is an existing solution for `pcap_fopen_offline()` that is suitable: on Windows export a hopen variant instead that takes a raw OS `HANDLE` and then make the API a wrapper macro around that.

Pull request to follow.

**Comment by guyharris** [comment]
On the one hand, making `pcap_dump_fopen()` a macro rather than a function potentially breaks binary compatibility with WinPcap and Npcap (and, if Npcap picks up the newer version of libpcap, with older versions of Npcap).

On the other hand, if you have a program that depends on WinPcap/Npcap exporting `pcap_dump_fopen()`, you have a program that has to be compiled with a compatible version of the CRT with which the library was built - and if, for example, WinPcap 4.1.3 and the current version of Npcap were built with incompatible CRTs (or, at least, incompatible at the C file-descriptor level), you have a program that depends on running with one of those two libraries, so binary compatibility might not exist *anyway*.

Plus, WinPcap exported `pcap_fopen_offline()` as a function until WinPcap 4..1, so they already broke binary compatibility there.

If some commercial product *really* depends on having those functions exported, they can just ship with the appropriate version of the library.

**Comment by guyharris** [comment]
Next time, just submit the pull request - that way, when I merge it, I don't have to remember to close the issue.
