### ISSUE TITLE
usb_read_linux_bin() fills packet length with incorrect values.

### ISSUE THREAD

**Issue by crabsmaps** [the-tcpdump-group/libpcap#808]
libpcap version: 1.8.1 
OS: Ubuntu's 18.10, Linux 4.15.0-46-generic

Statement of the problem:
`usb_read_linux_bin()` fills packet length with incorrect values.

Printing in callback I get 
```
pkth.len=61504
pkth.caplen=8208
usbmon_packet.length = 1048576
usbmon_packet.len_cap = 61440
```
While inspecting usbmon in text mode I can see line corresponding to the same packet:
`xxxxxxxxxxxxxxxx 2882903763 C Bi:4:006:1 0 1048576 = 00000000 00000000 00000600 00000600 00000000 00000000 00000000 06000000`
So 1048576 != 61504

I know that usbmon can truncate packets, but still I expect that pkth.len would be more than info.hdr->urb_len

**Comment by guyharris** [comment]
If `usbmon_packet` is a structure of the type give in the Linux kernel source's usbmon documentation:

    struct usbmon_packet {
    	u64 id;			/*  0: URB ID - from submission to callback */
    	unsigned char type;	/*  8: Same as text; extensible. */
    	unsigned char xfer_type; /*    ISO (0), Intr, Control, Bulk (3) */
    	unsigned char epnum;	/*     Endpoint number and transfer direction */
    	unsigned char devnum;	/*     Device address */
    	u16 busnum;		/* 12: Bus number */
    	char flag_setup;	/* 14: Same as text */
    	char flag_data;		/* 15: Same as text; Binary zero is OK. */
    	s64 ts_sec;		/* 16: gettimeofday */
    	s32 ts_usec;		/* 24: gettimeofday */
    	int status;		/* 28: */
    	unsigned int length;	/* 32: Length of data (submitted or actual) */
    	unsigned int len_cap;	/* 36: Delivered length */
    	union {			/* 40: */
    		unsigned char setup[SETUP_LEN];	/* Only for Control S-type */
    		struct iso_rec {		/* Only for ISO */
    			int error_count;
    			int numdesc;
    		} iso;
    	} s;
    	int interval;		/* 48: Only for Interrupt and ISO */
    	int start_frame;	/* 52: For ISO */
    	unsigned int xfer_flags; /* 56: copy of URB's transfer_flags */
    	unsigned int ndesc;	/* 60: Actual number of ISO descriptors */
    };				/* 64 total length */

then the two `usbmon_packet` fields are the ones identified in libpcap's `pcap/usb.h` as

    	uint32_t urb_len;
    	uint32_t data_len; /* amount of urb data really present in this event*/

So, in addition to the truncation done by the snapshot (which is done in userland), there's truncation done by the kernel usbmon mechanism, which is why `usbmon_packet.length` is 1048576 but `usbmon_packet.len_cap` is only 61440.

However, I'm not sure in what sense that's "truncation".  The code in `mon_bin.c` in the 4.20.3 kernel does:


	/*
	 * Find the maximum allowable length, then allocate space.
	 */
	urb_length = (ev_type == 'S') ?
	    urb->transfer_buffer_length : urb->actual_length;
	length = urb_length;

	if (usb_endpoint_xfer_isoc(epd)) {
		if (urb->number_of_packets < 0) {
			ndesc = 0;
		} else if (urb->number_of_packets >= ISODESC_MAX) {
			ndesc = ISODESC_MAX;
		} else {
			ndesc = urb->number_of_packets;
		}
		if (ev_type == 'C' && usb_urb_dir_in(urb))
			length = mon_bin_collate_isodesc(rp, urb, ndesc);
	} else {
		ndesc = 0;
	}
	lendesc = ndesc*sizeof(struct mon_bin_isodesc);

	/* not an issue unless there's a subtle bug in a HCD somewhere */
	if (length >= urb->transfer_buffer_length)
		length = urb->transfer_buffer_length;

	if (length >= rp->b_size/5)
		length = rp->b_size/5;

		...

	ep->len_urb = urb_length;
	ep->len_cap = length + lendesc;

This is probably not the

	if (length >= urb->transfer_buffer_length)
		length = urb->transfer_buffer_length;

truncation - a transfer shouldn't be larger than the buffer made available for it.

It might be the

	if (length >= rp->b_size/5)
		length = rp->b_size/5;

truncation.

**Comment by guyharris** [comment]
The default `b_size` is 300\*1024 (rounded up to a page boundary, but no CPU I know of has a smallest page size big enough to require rounding), and `b_size/5` is 61440, so that's the truncation that's happening here.

The buffer size can be set with a `MON_IOCT_RING_SIZE` ioctl.  The maximum is 1228800; if that was really a 1-megabyte transfer, we are, implicitly, applying a snapshot length to it, but not one set by the snapshot API, it's set by the default buffer size.

The buffer size definitions in `mon_bin.c`, and the comment before them, are

    /*
     * The magic limit was calculated so that it allows the monitoring
     * application to pick data once in two ticks. This way, another application,
     * which presumably drives the bus, gets to hog CPU, yet we collect our data.
     * If HZ is 100, a 480 mbit/s bus drives 614 KB every jiffy. USB has an
     * enormous overhead built into the bus protocol, so we need about 1000 KB.
     *
     * This is still too much for most cases, where we just snoop a few
     * descriptor fetches for enumeration. So, the default is a "reasonable"
     * amount for systems with HZ=250 and incomplete bus saturation.
     *
     * XXX What about multi-megabyte URBs which take minutes to transfer?
     */
    #define BUFF_MAX  CHUNK_ALIGN(1200*1024)
    #define BUFF_DFL   CHUNK_ALIGN(300*1024)
    #define BUFF_MIN     CHUNK_ALIGN(8*1024)
 
Unfortunately, `BUFF_MAX` gives a `b_size/5` of 245760, so you're *still* going to get your 1MB transfer truncated.

If a snapshot length is specified, we should use it to set the buffer size (based on the assumption that the maximum packet size is based on 1/5th of the buffer size); if a snapshot length *isn't* specified, we should set it based on the maximum buffer size (or, at least, what we think the USB monitor's maximum buffer size is; we're already forced to assume the 1/5, we might as well assume the maximum size as well), and set the buffer size to the maximum.

Then we probably need to set the on-the-wire length based on, among other things, the urb_length value.

**Comment by guyharris** [comment]
So a packet from binary usbmon has:

1) the fixed-length header - 48 bytes if not memory-mapped, 64 bytes if memory-mapped;
2) descriptors, for isochronous transfers;
3) `length` bytes of payload, where `length` is the variable in `mon_bin.c`.

So the captured data length is the sum of the fixed-length header length, the number of descriptors times the descriptor size, and `length`; the sum of the number of descriptors times the descriptor size and `length` is provided by `mon_bin.c` as the `len_cap` field in the kernel, which is the `data_len` field in libpcap's structure.

If we set the buffer size to `5*({snaplen} - {fixed-length header len}), that should make it big enough for a snaplen-length packet; if there are descriptors for a maximum-length packet, we'll end up discarding, in libpcap, `{number of descriptors}*{descriptor size}` bytes of data at the end of the packet, even though it's delivered to us from the kernel.  So it goes.

If that value is bigger than `BUFF_MAX`, we clamp it to `BUFF_MAX`, and then claim the snapshot length is `BUFF_MAX/5 + {fixed-length header len}`.

**Comment by guyharris** [comment]
And the "on-the-bus length" of the packet (even though that's not exactly what was sent on the bus) is the sum of:

1) the length of the fixed-length header;
2) the length of the descriptors;
3) the actual amount of transferred data.

Most of the time, that would be `{fixed-length header len} + ({number of descriptors}*{descriptor size}) + {len_urb from the header}`; `len_urb` in the kernel's header structure is `urb_len` in libpcap's header structure.

For isochronous `'C'` transfers, `urb_len` isn't set to something valid, as I infer from the comment

    /*
     * This is the look-ahead pass in case of 'C Zi', when actual_length cannot
     * be used to determine the length of the whole contiguous buffer.
    */

before `mon_bin_collate_isodesc()` - but the un-truncated value of `mon_bin_collate_isodesc()` is *not provided by the kernel*, so we're kinda screwed there.  Maybe we take the maximum of the captured length and the length calculated from `urb_len`.

**Comment by crabsmaps** [comment]
Also it is rather strange that urb_len is used in `usb_read_linux()` and not in `usb_read_linux_bin()`
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-usb-linux.c#L871
https://github.com/the-tcpdump-group/libpcap/blob/master/pcap-usb-linux.c#L1084

Is there a way to force usage of usbmon text API in libpcap to check whether they are agreeing on the matter?

**Comment by guyharris** [comment]
> Also it is rather strange that urb_len is used in `usb_read_linux()` and not in `usb_read_linux_bin()`

Or maybe it just means that `usb_read_linux_bin()` - and `usb_read_linux_mmap()` - are wrong.

> Is there a way to force usage of usbmon text API in libpcap to check whether they are agreeing on the matter?

None other than modifying libpcap.

**Comment by guyharris** [comment]
At least in my tests, not all packets having a non-zero `urb_len` involve any data transfer according to `data_len`, so it's not as simple as "always use `urb_len` to get the on-the-bus packet length".

**Comment by guyharris** [comment]
Unless the `flag_data` field in the header is 0 (or perhaps '='), meaning "data present", there's no data, and `urb_len` should *NOT* be used to generate the on-the-bus length - the on-the-bus length should be calculated based on `data_len` (which *should*, I suspect, be 0 in this case, but using it means we can't get weird packets with caplen > len).

**Comment by guyharris** [comment]
Change 4ccdc8a3cbf5195a7c089002136e53db541b36ba should fix this.
