### ISSUE TITLE
Missing Dependancies

### ISSUE THREAD

**Issue by Ericreh** [the-tcpdump-group/libpcap#830]
I'm trying to cross-compile libpcap in Visual Studio with VisualGDB. However, when I try to build the project with a simple test program, it alerts me I'm missing dlpi.h and stream.h. I'm not sure where these files come from (SunOS, maybe?), or why it's looking for them. Is anyone able to point me in the right direction to grab these so it'll build?

**Comment by guyharris** [comment]
[The home page for VisualGDB](https://visualgdb.com) seems to speak of it as being for building projects for *Linux* using Visual Studio; if you're trying to include `dlpi.h`, you're not building for *Linux*.

Note also that the libpcap source includes files for three ways of configuring and building:

1. autotools (`./configure`), which we support for UN\*Xes but not for Windows;

1. [CMake](https://cmake.org), which we support for UN\*Xes and for Windows;

1. Visual Studio files.

All developers should, as necessary, update the autotools and CMake files; we do test builds for autotools on Linux and macOS, and for CMake on Linux, macOS, and Windows, to try to catch cases where that's done.

The Visual Studio files, on the other hand, are *not* being maintained by most developers; unlike CMake, where, if a user adds a new source file that's used on *all* platforms, it shouldn't matter what platform they do it on, it should work for all platforms, for the Visual Studio files you have to know what to change manually or have to use Visual Studio (which may be hard to do on non-WIndows platforms) and would probably need Windows on which to test it.  Many developers are working only on some UN\*X, so that's not going to happen.

So, for building *for* Windows *on* Windows, you should be using CMake.

We do not guarantee that cross-development on Windows for a UN\*X (such as Linux) will work using CMake, although we might be willing to fix it, with the help of a knowledgable developer doing the cross-development, if that's not too disruptive.  A user who expects for-Linux-on-Windows cross-development to work out of the box may be disappointed.

We do not even guarantee that *native* development for Windows will work with the project files we ship; cross-development is even less likely to work.

So your problem is a *lot* bigger than what you think it is, and getting some SunOS 5 header files is *not* going to help here (I doubt you're cross-compiling for Solaris).
