### ISSUE TITLE
Questions about checksums in packets sent with pcap_sendpacket()

### ISSUE THREAD

**Issue by katoge** [the-tcpdump-group/libpcap#917]
Hello,

Is it possible to send a packet with setting checksum of IP and TCP to zero and let the NIC calculate it? Maybe I lack in experience how pcap_sendpacket() processes it.
I cannot capture the Ethernet-Frame CRC, because NIC strips it off.
Do I have to build the CRC part too before using send_packet()? Or does send_packet() forwards the packet to the NIC which extends it?

**Comment by guyharris** [comment]
Presumably by `send_packet()` you mean `pcap_sendpacket()`.  (Note that everything here also applies to `pcap_inject()`; they're just two APIs for the same mechanism, provided because WinPcap added one and OpenBSD's libpcap added the other, and we wanted to support code written for either API.)

> Is it possible to send a packet with setting checksum of IP and TCP to zero and let the NIC calculate it?

If you send a packet with IP and TCP checksums of zero, then:

- if the NIC doesn't support calculating the checksum, the packet will be sent with zero checksums;

- if the NIC does support that, but that option is disabled by the driver (perhaps as a result of some *other* software telling it to do so) or is not enabled by the driver, the packet will be sent with zero checksums;

- if the NIC supports that, and the feature is enabled, and the driver causes checksums to be calculated by the NIC for packets injected via the code path used for raw packet injection, the checksums will be calculated by the NIC, otherwise they won't and the packet will be sent with zero checksums.

Whether all that is true depends on the NIC, the driver, and the rest of the OS software, so there's no general answer for all OSes.  pcap currently provides no API to query whether a packet sent via `pcap_sendpacket()`/`pcap_inject()` which checksums, if any, will be calculated.

> I cannot capture the Ethernet-Frame CRC, because NIC strips it off.

With at least some NICs and at least some versions of some drivers in some OSes, the CRC isn't stripped.  Wireshark has heuristics to detect whether the CRC is present or not because some NICs used by some Macs, with the Mac OS X driver (yes, "Mac OS X" - that tells you how long ago that was!), provided the CRC for captured incoming packets (but not outgoing packets).

On Linux, at least some NIC/driver combinations may be configurable to 1) capture packets with an invalid CRC and 2) include the CRC in the packet by using ethtool ioctls and thus by ethtool commands.  I have not tried that (the only Linux "boxes" I have to try it on are made by a company named "VMware" :-), so I don't know whether the virtual NIC provides a CRC or not), and pcap currently has no APIs to request that type of "raw capture" mode (think of it as "monitor mode for Ethernet").

> Do I have to build the CRC part too before using send_packet()?

No.

> Or does send_packet() forwards the packet to the NIC which extends it?

Yes.

**Comment by katoge** [comment]
I appreciate your answer in so short time! Thank you! Nice to hear that my effort on creating own functions to calculate IP and TCP checksums was worth it.

**Comment by stefenson** [comment]
I get a similar problem about checksum.

My problem is TCP checksum appears to have been tampered after pcap_sendpacket().

My environment is Win10 PC, and develop with winpcap, which I know is no longer maintained.

Interestingly, the checksum in first Packet that TCP client send (SYN) is correct (calculate by my program), but the checksum in other packet after the first on will go wrong. However, the calculate function is in same.

And more information, I tried to make the checksum 0x0000 for all packet, I found that every checksum in every packet will be changed except the first one (the first one still is 0x0000).

My network card is Marvell AVASTAR Wireless-AC Network Controller.

Would you please give me some suggestions?
