### ISSUE TITLE
WinPcap fails on AppVeyor

### ISSUE THREAD

**Issue by gvanem** [the-tcpdump-group/libpcap#923]
As a test of installing WinPcap on AppVeyor  (which I need in another project), I
fail to get any libpcap program to work on AppVeyor; the program just hangs.

Basically I did:
  * Created a [semi-fork](https://github.com/gvanem/libpcap) of libpcap
 * Added a [`cinst winpcap`](https://github.com/gvanem/libpcap/blob/master/.appveyor.yml#L30) to the `.appveyor.yml` file. 
 * Added  a [`test_script:`](https://github.com/gvanem/libpcap/blob/master/.appveyor.yml#L68) that simply calls `run\rpcapd.exe`
* This program never start properly; No `Press CTRL + C to stop the server...` message. 
An example AppVeyor job is here:
https://ci.appveyor.com/project/gvanem/libpcap-hnqqx/builds/32269806/job/5e5sf4yt1x4rc47v
(note the hang on last line).

I'm not sure who's fault it is. Maybe AppVeyor doesn't allow `npf.sys` or it's service to run?
Or maybe the `cinst winpcap` isn't done properly.

**Comment by mcr** [comment]
(I hate how distracting the number of warnings coming out that build is)

    echo Trying to run 'run\rpcapd.exe' with the above 'winpcap' installation
    Trying to run 'run\rpcapd.exe' with the above 'winpcap' installation
    run\rpcapd.exe

AFAIK, rpcapd.exe would attempt to open the capture device, and I can't see how you'd permission to do that on AppVeyor.   I don't think that's a good way to test the library, alas.

**Comment by gvanem** [comment]
> (I hate how distracting the number of warnings coming out that build is)

MinGW is a bitch when it comes to printf-warnings.

> and I can't see how you'd permission to do that on AppVeyor. I don't think that's a good 
> way to test the library, alas.

I've heard NPcap has a *silent* installer. Maybe that would work better? A real pity otherwise.

**Comment by fxlb** [comment]
Only with Npcap OEM?
"Silent installer—Npcap OEM includes a silent installation option (/S)"
https://nmap.org/npcap/oem/redist.html

**Comment by gvanem** [comment]
There is a fork of this *NMAP silent installer* here: https://github.com/mfontanini/winpcap-installer

Besides [PcapPlusplus](https://github.com/seladb/PcapPlusPlus) seems to use WinPcap on [Appveyor](
https://ci.appveyor.com/project/seladb/pcapplusplus). I'll check it out.

**Comment by pavel-kirienko** [comment]
I seem to be facing a similar issue where my application that leverages WinPCap operates correctly in my local virtual machine with Windows 10 (managed by VirtualBox), but fails to capture any packets when run in an AppVeyor Windows pipeline. My setup is otherwise functional: the very same application functions correctly when run in a GNU/Linux pipeline using libpcap (also on AppVeyor). I am capturing packets from all interfaces so it is not likely that I chose the wrong interface.

@gvanem have you been able to resolve this issue?

**Comment by gvanem** [comment]
> have you been able to resolve this issue?

No.

**Comment by mcr** [comment]
It is very unlikely that the AppVeyor system gives you permission to capture
packets.

**Comment by infrastation** [comment]
It looks like this effect is a peculiarity of Appveyor, in which case this issue is not actionable and the best next stop would be Appveyor tech support. Maybe some different Windows CI service works better in this regard (Cirrus CI is not difficult to figure out, for example). If anyone can tell the reason to keep this issue open, please do. Otherwise it will be closed in 7 days.

**Comment by pavel-kirienko** [comment]
I actually managed to get it to work with AppVeyor, although I am now using Npcap. WFIW, here is my recipe:

https://github.com/UAVCAN/pyuavcan/blob/9da3cf579b65cae4067b16c621cc3321156f17d4/.appveyor.yml#L46-L52

**Comment by gvanem** [comment]
@pavel-kirienko This looks pretty cool. I'll try the `shutdown ..` command.

**Comment by infrastation** [comment]
It is time.
