### ISSUE TITLE
About Linux capabilities

### ISSUE THREAD

**Issue by fxlb** [the-tcpdump-group/libpcap#926]
pcap.3pcap.in states:

`you  must have [...] and CAP_NET_ADMIN to enumerate network devices with, for example, the -D
flag`

But without this capability, the -D option works for a "normal" user on Debian.

Should we update the manual or did I miss something?

**Comment by Oppen** [comment]
Are you running with `sudo`?

**Comment by guyharris** [comment]
> pcap.3pcap.in states:
> 
> `you must have [...] and CAP_NET_ADMIN to enumerate network devices with, for example, the -D flag`
> 
> But without this capability, the -D option works for a "normal" user on Debian.
> 
> Should we update the manual or did I miss something?

We should update the manual.

On older Linux systems, `getifaddrs()` wasn't available (or with older libpcaps that had `pcap_findalldevs()`, it wasn't used), so it had to do an `SIOCGIFCONF` ioctl and then do other ioctls, including `SIOCGIFFLAGS`, and the latter required `CAP_NET_ADMIN` capabilities.  Newer kernels appear not to require `CAP_NET_ADMIN` just to *get* the device flags.

In addition, tests were done to make sure that the device could be opened, requiring `CAP_NET_RAW`; those tests were removed so that you can enumerate devices even if you don't have permission to open them, so the error you get if you don't have enough permission to capture is "you don't have permission", not "sorry, there are no devices" - the latter was harder to diagnose if a user reported it (and that happened enough with Wireshark mailing lists that I decided to change it).

**Comment by guyharris** [comment]
Fixed in 7763eb4c55ab257adde1064c4c5fc7dffd6604d5.
