### ISSUE TITLE
enter_rfmon_mode_wext() may fail due to ioctl(SIOCGIWPRIV) bug

### ISSUE THREAD

**Issue by m00k12** [the-tcpdump-group/libpcap#941]
libpcap-1.9.x
linux 4.19 onwards

It looks like there is a kernel bug, from at least 4.19 onwards which means that `ioctl(SIOCGIWPRIV)` fails to return the count of private commands when returning `E2BIG`.  The bug is that on the error return path, the userspace request buffer is not updated, which means the `ireq.u.data.length` field remains zero in `enter_rfmon_mode_wext()` after the first call to `ioctl(SIOCGIWPRIV)`.

The second call to `SIOCGIWPRIV` in `enter_rfmon_mode_wext()` therefore also returns `E2BIG` (as the length is still zero) and the error path is taken out of the function - monitor mode fails to start.  There are various reports of `pcap_activate()` failing with 'SIOCGIWPRIV: Argument list too long' around the web which I think are due to this.

Not every wireless driver is affected.  Firstly if the driver does not support private ioctls() and `EOPNOTSUPP` is returned on the first `SIOCGIWPRIV` attempt, this code path is skipped.  A very quick look at the kernel sources made me think in-tree wireless drivers don't use private ioctl functions - I may be wrong.

Also if HAVE_LIBNL is defined and `enter_rfmon_mode_mac80211()` succeeds, this code path is also skipped and things should work.

A reasonable workaround for this is to check if `ireq.u.data.length` is still zero after the first ioctl() attempt.  In that case, setting that field to some arbitrary value (e.g.64) before the malloc() and retry will probably work for most drivers as the expense of a bit of over-allocation for a short period of time.    

Please see the following comment I placed against the rtl8812au driver for more background on the kernel side:

https://github.com/aircrack-ng/rtl8812au/issues/441#issuecomment-640716935

**Comment by guyharris** [comment]
Is there any reason to use something *other* than libpcap's "use a Netlink socket to do the stuff that airmon-ng does" mechanism any more?  Currently, few if any distributions built it with libnl (the problem is that a library using one version of libnl, called by an application using another version of libnl, causes calls to the version of libnl *not* linked in not to work), but the old Wireless Extensions APIs often get frustrated by NetworkManager or equivalent mechanisms.

The only thing the Wireless Extensions, etc. code path does is work with non-mac80211 drivers; are there enough of them still around to make it worthwhile supporting them?  Or should we just get rid of the Wireless Extensions code, just as we've gotten rid of other code needed only with older versions of the kernel?

**Comment by jmberg** [comment]
We've been trying to deprecate the wext stuff upstream for 15 years. And even back then, there probably was better API for what this is trying to do, though "set_prismhdr" probably didn't exist, but if you really need a prism device still, then use p54 instead of prism54 driver. (In fact, we want to also kill that driver)

"monitor_type" seems to exist upstream, "forceprismheader" doesn't. Neither do "forceprism", "prismhdr", "rfmontx". "monitor" does, but all of these are in drivers for *ancient* devices, all of them are >15 years old. Probably more like 20.

If there's a current driver that's doing something like this, it stands zero chances of getting into upstream Linux, it has to be adapted/rewritten to the modern netlink APIs. Supoorting this here is just more incentive for driver writers to not join the current millennium. (OK, I jest, we only started with the netlink APIs in 2005.)

Kill it with fire!

**Comment by m00k12** [comment]
> Is there any reason to use something _other_ than libpcap's "use a Netlink socket to do the stuff that airmon-ng does" mechanism any more?

@guyharris - I don't think so, but libpcap will happily configure and build without libnl and without any warning in such a setup. If a definition of IW_MODE_MONITOR is found (in linux/wireless.h), it pulls this code in at _compile_ time.  I'm cross-compiling and have ended up in this situation, somewhat by accident though will fix it for me.  Others may have ended up with this config too - Googling exactly "pcap_activate() SIOCGIWPRIV: Argument list too long" shows this crops up fairly frequently and recently too.

I like @jmberg's idea to kill it with fire, but if libpcap is more conservative than that, perhaps the one line workaround could go in along with making lack of libnl a warning at configure time.  Simply dropping the code will mean that people with a setup that currently doesn't work with libpcap, still won't work, but for a different reason they have to figure out for themselves.

**Comment by m00k12** [comment]
For completeness, here's a patch which works around the kernel bug where it doesn't really return the private ioctl() count.  This should make configs that are relying on wext to work with drivers that have private ioctls():
```patch
--- libpcap-1.9.1/pcap-linux.c	2019-09-30 15:39:22.000000000 +0100
+++ libpcap-1.9.1-patch/pcap-linux.c	2020-06-09 07:12:58.604851941 +0100
@@ -6022,6 +6022,14 @@ enter_rfmon_mode_wext(pcap_t *handle, in
 		}
 
 		/*
+		 * Ok, kernel didn't return the count of private ioctls.
+		 *  Guess there are no more than 64.
+		 */
+		if (ireq.u.data.length == 0) {
+		    ireq.u.data.length = 64;
+		}
+
+		/*
 		 * OK, try to get the list of private ioctls.
 		 */
 		priv = malloc(ireq.u.data.length * sizeof (struct iw_priv_args));
```

**Comment by guyharris** [comment]
> I like @jmberg's idea to kill it with fire, but if libpcap is more conservative than that, perhaps the one line workaround could go in along with making lack of libnl a warning at configure time. Simply dropping the code will mean that people with a setup that currently doesn't work with libpcap, still won't work, but for a different reason they have to figure out for themselves.

The "different reason" would be something like

    $ ./tcpdump -I -i en0 
    tcpdump: en0: That device doesn't support monitor mode

(on macOS with a quickly-hacked libpcap to remove monitor mode support, but the same would happen on Linux, albeit with a different device name), or Wireshark not offering the monitor mode checkbox at all.  Hopefully that's less of a weird error situation than completely weird failures (either from tis bug or from NetworkMonitor "helpfully" turning monitor mode off out from under the user).

**Comment by jmberg** [comment]
> tcpdump: en0: That device doesn't support monitor mode

That doesn't seem completely unreasonable, after all it then doesn't really support monitor mode - the way libpcap would support it at least. Dunno.

**Comment by guyharris** [comment]
> Hopefully that's less of a weird error situation than completely weird failures (either from tis bug or from NetworkMonitor "helpfully" turning monitor mode off out from under the user).

Which is apparently what's happening on Ubuntu 20.04 - after going through the painful process of enabling packet capture (I apparently had to not only log out, but *reboot*, in order to be in group "wireshark"!), if I tried checking the "Monitor mode" checkbox for the Wi-Fi adapter on my (virtual) machine, it got un-checked shortly afterwards.

Many users have complained about this.

I think that you need to have a separate "monitor mode" device to avoid monitor mode being "helpfully" turned off.  Life's too short to deal with all the old pre-mac80211 stuff, so I'm yanking it out.

**Comment by guyharris** [comment]
The code in question is no longer in `pcap-linux.c`.
