### ISSUE TITLE
[new feature] Getting the default gateway for an activated device.

### ISSUE THREAD

**Issue by venetwork** [the-tcpdump-group/libpcap#951]
Hello.

It would be nice if libpcap could retrieve the default gateway of an activated device just as it can get its IP address and mask. It's possible in PcapPlusPlus:

printf("   Default gateway:       %s\n", dev->getDefaultGateway().toString().c_str());

(https://pcapplusplus.github.io/docs/tutorials/capture-packets)

Why not make it available in libpcap too? :)

Cheers.

**Comment by mcr** [comment]
So, IPv4, IPv6, when there are policy routes (where the default depends on the source address: SADR), when there are no addresses assigned.    
How would it do network namespaces?
And then there are RFC7556 MIF issues too!
I think that this definitely outside of the space of libpcap, and that's why that library is called "pcap" PLUS PLUS.  

To do this, libpcap would have to open a variety of different socket types (for different OSes) and listen to a bunch of things.
It seems like this is all sufficiently divorced from packet capture that some other "plusplus" library could be created, and I think that PcapPlusPlus has already done this, but I guess you need this in C?

**Comment by venetwork** [comment]
I knew it was a longshot but I had to try. :)

From what I understand there are at least three ways this can be done on Linux - my target platform. Two of them are described here:

https://gist.github.com/javiermon/6272065

(the netlink one does what you described)

The last one is very crude: just invoke a Linux command from within your code that can print the default gateway (ip and/or netstat with proper parameters if I'm not mistaken) and save the result to a variable.

I'll probably go with parsing the /proc/net/route file as the netlink solution is way too complex (and lengthy) for my code. The third method, on the other hands, is way too curde for me. :)

Thanks for you response anyway!

Cheers.

**Comment by infrastation** [comment]
I had worked on routing protocols in a C software that tried to maintain compatibility with a number of Unix-like OSes (and their kernels), and I agree with Michael: as soon as you state this problem properly, you don't want to start solving it because it is too much work, and if you don't state it properly, the solution is going to be questionable.

To me it seems that a shell script that sets a variable to be used in the filter expression would be an OK first version.
