### ISSUE TITLE
Public function for data link end offset in a packet based on interface type.

### ISSUE THREAD

**Issue by ppetrica** [the-tcpdump-group/libpcap#968]
Hi, I haven't been able to find a publicly exposed function which would allow the user to find the offset into the packet to the end of the datalink layer. Would it be possible for libpcap to expose such a function?
I know that libpcap generates the right filters for different types of interface and the offset is calculated here:
https://github.com/the-tcpdump-group/libpcap/blob/master/gencode.c#L1218

**Comment by infrastation** [comment]
it would help to state this problem in more specific terms. What would be the best way to tell where the data link header ends and the payload starts?

**Comment by guyharris** [comment]
> I haven't been able to find a publicly exposed function which would allow the user to find the offset into the packet to the end of the datalink layer

There isn't one.

Doing so is part of the process of interpreting a packet's contents, and libpcap isn't a packet-parsing library; such a function really belongs in a separate packet-parsing library.

The only packet parsing libpcap understands is

1. generating filters;
2. putting some fields in pseudo-headers into host byte order when reading from a "byte-swapped" pcap file or pcapng file section.

> I know that libpcap generates the right filters for different types of interface and the offset is calculated here:
https://github.com/the-tcpdump-group/libpcap/blob/master/gencode.c#L1218

The offset *for Ethernet* is set there.  Ethernet is *not* the only link-layer type libpcap supports, and libpcap does *not* directly calculate the offset for all of them  See, for example, https://github.com/the-tcpdump-group/libpcap/blob/master/gencode.c#L1326, which is (as of this instant in time) the first of the lines that handles the offset for 802.11.  There *is* no constant value for the offset from the beginning of the 802.11 link-layer to the beginning of the 802.11 payload - the 802.11 header is *variable length*, and can differ from packet to packet.

Furthermore, the *interpretation* of the payload is not always the same - it depends on the frame type.  In *most* cases, *if* the frame is a data frame (and has been decrypted if it's on a protected network!), an 802.2 LLC header follows the link-layer header, either with the payload directly following the 802.2 LLC header or with a SNAP header following the 802.2 LLC header and the payload following the SNAP header.  However, if the frame is a *management* frame, there's no 802.2 LLC header, and the payload isn't, for example, an IP packet.  (And in some automotive uses of 802.11, there's no 802.2 LLC header, there's a header that directly contains an Ethertype.)

On top of that, there are also metadata headers that may precede the link-layer header; for "radiotap+802.11", there's a radiotap header, giving radio metadata, preceding the 802.11 header, and the radiotap header isn't fixed-length, either.

If the payload (in the sense of, for example, an IP packet) isn't at a fixed offset from the beginning of the packet data, libpcap does *not* calculate the offset - it generates, as part of the filter code, BPF instructions that calculate the offset, *based on the packet data*, *at the time the filter is applied*.  There's no code in libpcap to calculate the offset directly.

Neither tcpdump nor Wireshark have routines that "find the offset into the packet to the end of the datalink layer" - they just have routines that parse all the layers of the packet individually, based on the link-layer type and on the bytes in the packet data.  This isn't simple code, because this isn't a simple problem.

**Comment by infrastation** [comment]
Well, then the only reasonable thing to do about this request is to close it, correct?

**Comment by ppetrica** [comment]
Thank you for the detailed and insightful reply. I only needed to know the offset for a couple of data link types but thought it may be useful to include such a function since libpcap is aware of all of the packet details, however I haven't considered the implications and it seems like there's no simple solution to this problem. For my simple use case, nmap's solution was enough and is what I used at the time, noting it here in case someone needs it.

https://github.com/nmap/nmap/blob/master/libnetutil/netutil.cc#L4096
