### ISSUE TITLE
Can't capture Dot1Q packets with priority=6

### ISSUE THREAD

**Issue by considerTCP** [the-tcpdump-group/libpcap#998]
A TCPDump with BPF that contains "vlan XXX", do not  capture packets with Dot1Q priority=6 (internetwork).

TCPDUMP version: 4.9.2
LIBPCAP version 1.8.1

**Comment by guyharris** [comment]
If this is on Linux, try it with libpcap version 1.10.0 (no need to change the tcpdump version, this is a libpcap issue, which is why I moved it to the libpcap repository).

You may have to download both libpcap and tcpdump source and build them together; unpack the source tarballs into subdirectories of the same directory, so you have XXX/libpcap-1.10.0 and XXX/tcpdump-4.{whatever}, run the configure script for libpcap and build it, then run the configure script for tcpdump (which should find libpcap in ../libpcap-1.10.0) and build it.

**Comment by infrastation** [comment]
Looks like this problem has been addressed, or did not happen in the first place, so closing.
